// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/so/ent/predicate"
	"github.com/lightsparkdev/spark/so/ent/signingkeyshare"
)

// SigningKeyshareQuery is the builder for querying SigningKeyshare entities.
type SigningKeyshareQuery struct {
	config
	ctx        *QueryContext
	order      []signingkeyshare.OrderOption
	inters     []Interceptor
	predicates []predicate.SigningKeyshare
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SigningKeyshareQuery builder.
func (skq *SigningKeyshareQuery) Where(ps ...predicate.SigningKeyshare) *SigningKeyshareQuery {
	skq.predicates = append(skq.predicates, ps...)
	return skq
}

// Limit the number of records to be returned by this query.
func (skq *SigningKeyshareQuery) Limit(limit int) *SigningKeyshareQuery {
	skq.ctx.Limit = &limit
	return skq
}

// Offset to start from.
func (skq *SigningKeyshareQuery) Offset(offset int) *SigningKeyshareQuery {
	skq.ctx.Offset = &offset
	return skq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (skq *SigningKeyshareQuery) Unique(unique bool) *SigningKeyshareQuery {
	skq.ctx.Unique = &unique
	return skq
}

// Order specifies how the records should be ordered.
func (skq *SigningKeyshareQuery) Order(o ...signingkeyshare.OrderOption) *SigningKeyshareQuery {
	skq.order = append(skq.order, o...)
	return skq
}

// First returns the first SigningKeyshare entity from the query.
// Returns a *NotFoundError when no SigningKeyshare was found.
func (skq *SigningKeyshareQuery) First(ctx context.Context) (*SigningKeyshare, error) {
	nodes, err := skq.Limit(1).All(setContextOp(ctx, skq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{signingkeyshare.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (skq *SigningKeyshareQuery) FirstX(ctx context.Context) *SigningKeyshare {
	node, err := skq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SigningKeyshare ID from the query.
// Returns a *NotFoundError when no SigningKeyshare ID was found.
func (skq *SigningKeyshareQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = skq.Limit(1).IDs(setContextOp(ctx, skq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{signingkeyshare.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (skq *SigningKeyshareQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := skq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SigningKeyshare entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SigningKeyshare entity is found.
// Returns a *NotFoundError when no SigningKeyshare entities are found.
func (skq *SigningKeyshareQuery) Only(ctx context.Context) (*SigningKeyshare, error) {
	nodes, err := skq.Limit(2).All(setContextOp(ctx, skq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{signingkeyshare.Label}
	default:
		return nil, &NotSingularError{signingkeyshare.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (skq *SigningKeyshareQuery) OnlyX(ctx context.Context) *SigningKeyshare {
	node, err := skq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SigningKeyshare ID in the query.
// Returns a *NotSingularError when more than one SigningKeyshare ID is found.
// Returns a *NotFoundError when no entities are found.
func (skq *SigningKeyshareQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = skq.Limit(2).IDs(setContextOp(ctx, skq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{signingkeyshare.Label}
	default:
		err = &NotSingularError{signingkeyshare.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (skq *SigningKeyshareQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := skq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SigningKeyshares.
func (skq *SigningKeyshareQuery) All(ctx context.Context) ([]*SigningKeyshare, error) {
	ctx = setContextOp(ctx, skq.ctx, ent.OpQueryAll)
	if err := skq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SigningKeyshare, *SigningKeyshareQuery]()
	return withInterceptors[[]*SigningKeyshare](ctx, skq, qr, skq.inters)
}

// AllX is like All, but panics if an error occurs.
func (skq *SigningKeyshareQuery) AllX(ctx context.Context) []*SigningKeyshare {
	nodes, err := skq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SigningKeyshare IDs.
func (skq *SigningKeyshareQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if skq.ctx.Unique == nil && skq.path != nil {
		skq.Unique(true)
	}
	ctx = setContextOp(ctx, skq.ctx, ent.OpQueryIDs)
	if err = skq.Select(signingkeyshare.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (skq *SigningKeyshareQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := skq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (skq *SigningKeyshareQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, skq.ctx, ent.OpQueryCount)
	if err := skq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, skq, querierCount[*SigningKeyshareQuery](), skq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (skq *SigningKeyshareQuery) CountX(ctx context.Context) int {
	count, err := skq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (skq *SigningKeyshareQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, skq.ctx, ent.OpQueryExist)
	switch _, err := skq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (skq *SigningKeyshareQuery) ExistX(ctx context.Context) bool {
	exist, err := skq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SigningKeyshareQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (skq *SigningKeyshareQuery) Clone() *SigningKeyshareQuery {
	if skq == nil {
		return nil
	}
	return &SigningKeyshareQuery{
		config:     skq.config,
		ctx:        skq.ctx.Clone(),
		order:      append([]signingkeyshare.OrderOption{}, skq.order...),
		inters:     append([]Interceptor{}, skq.inters...),
		predicates: append([]predicate.SigningKeyshare{}, skq.predicates...),
		// clone intermediate query.
		sql:  skq.sql.Clone(),
		path: skq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SigningKeyshare.Query().
//		GroupBy(signingkeyshare.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (skq *SigningKeyshareQuery) GroupBy(field string, fields ...string) *SigningKeyshareGroupBy {
	skq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SigningKeyshareGroupBy{build: skq}
	grbuild.flds = &skq.ctx.Fields
	grbuild.label = signingkeyshare.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.SigningKeyshare.Query().
//		Select(signingkeyshare.FieldCreateTime).
//		Scan(ctx, &v)
func (skq *SigningKeyshareQuery) Select(fields ...string) *SigningKeyshareSelect {
	skq.ctx.Fields = append(skq.ctx.Fields, fields...)
	sbuild := &SigningKeyshareSelect{SigningKeyshareQuery: skq}
	sbuild.label = signingkeyshare.Label
	sbuild.flds, sbuild.scan = &skq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SigningKeyshareSelect configured with the given aggregations.
func (skq *SigningKeyshareQuery) Aggregate(fns ...AggregateFunc) *SigningKeyshareSelect {
	return skq.Select().Aggregate(fns...)
}

func (skq *SigningKeyshareQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range skq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, skq); err != nil {
				return err
			}
		}
	}
	for _, f := range skq.ctx.Fields {
		if !signingkeyshare.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if skq.path != nil {
		prev, err := skq.path(ctx)
		if err != nil {
			return err
		}
		skq.sql = prev
	}
	return nil
}

func (skq *SigningKeyshareQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SigningKeyshare, error) {
	var (
		nodes = []*SigningKeyshare{}
		_spec = skq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SigningKeyshare).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SigningKeyshare{config: skq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(skq.modifiers) > 0 {
		_spec.Modifiers = skq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, skq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (skq *SigningKeyshareQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := skq.querySpec()
	if len(skq.modifiers) > 0 {
		_spec.Modifiers = skq.modifiers
	}
	_spec.Node.Columns = skq.ctx.Fields
	if len(skq.ctx.Fields) > 0 {
		_spec.Unique = skq.ctx.Unique != nil && *skq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, skq.driver, _spec)
}

func (skq *SigningKeyshareQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(signingkeyshare.Table, signingkeyshare.Columns, sqlgraph.NewFieldSpec(signingkeyshare.FieldID, field.TypeUUID))
	_spec.From = skq.sql
	if unique := skq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if skq.path != nil {
		_spec.Unique = true
	}
	if fields := skq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, signingkeyshare.FieldID)
		for i := range fields {
			if fields[i] != signingkeyshare.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := skq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := skq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := skq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := skq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (skq *SigningKeyshareQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(skq.driver.Dialect())
	t1 := builder.Table(signingkeyshare.Table)
	columns := skq.ctx.Fields
	if len(columns) == 0 {
		columns = signingkeyshare.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if skq.sql != nil {
		selector = skq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if skq.ctx.Unique != nil && *skq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range skq.modifiers {
		m(selector)
	}
	for _, p := range skq.predicates {
		p(selector)
	}
	for _, p := range skq.order {
		p(selector)
	}
	if offset := skq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := skq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (skq *SigningKeyshareQuery) ForUpdate(opts ...sql.LockOption) *SigningKeyshareQuery {
	if skq.driver.Dialect() == dialect.Postgres {
		skq.Unique(false)
	}
	skq.modifiers = append(skq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return skq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (skq *SigningKeyshareQuery) ForShare(opts ...sql.LockOption) *SigningKeyshareQuery {
	if skq.driver.Dialect() == dialect.Postgres {
		skq.Unique(false)
	}
	skq.modifiers = append(skq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return skq
}

// SigningKeyshareGroupBy is the group-by builder for SigningKeyshare entities.
type SigningKeyshareGroupBy struct {
	selector
	build *SigningKeyshareQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (skgb *SigningKeyshareGroupBy) Aggregate(fns ...AggregateFunc) *SigningKeyshareGroupBy {
	skgb.fns = append(skgb.fns, fns...)
	return skgb
}

// Scan applies the selector query and scans the result into the given value.
func (skgb *SigningKeyshareGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, skgb.build.ctx, ent.OpQueryGroupBy)
	if err := skgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SigningKeyshareQuery, *SigningKeyshareGroupBy](ctx, skgb.build, skgb, skgb.build.inters, v)
}

func (skgb *SigningKeyshareGroupBy) sqlScan(ctx context.Context, root *SigningKeyshareQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(skgb.fns))
	for _, fn := range skgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*skgb.flds)+len(skgb.fns))
		for _, f := range *skgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*skgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := skgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SigningKeyshareSelect is the builder for selecting fields of SigningKeyshare entities.
type SigningKeyshareSelect struct {
	*SigningKeyshareQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sks *SigningKeyshareSelect) Aggregate(fns ...AggregateFunc) *SigningKeyshareSelect {
	sks.fns = append(sks.fns, fns...)
	return sks
}

// Scan applies the selector query and scans the result into the given value.
func (sks *SigningKeyshareSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sks.ctx, ent.OpQuerySelect)
	if err := sks.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SigningKeyshareQuery, *SigningKeyshareSelect](ctx, sks.SigningKeyshareQuery, sks, sks.inters, v)
}

func (sks *SigningKeyshareSelect) sqlScan(ctx context.Context, root *SigningKeyshareQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sks.fns))
	for _, fn := range sks.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sks.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sks.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
