// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lightsparkdev/spark/so/ent/predicate"
	"github.com/lightsparkdev/spark/so/ent/usersignedtransaction"
)

// UserSignedTransactionDelete is the builder for deleting a UserSignedTransaction entity.
type UserSignedTransactionDelete struct {
	config
	hooks    []Hook
	mutation *UserSignedTransactionMutation
}

// Where appends a list predicates to the UserSignedTransactionDelete builder.
func (ustd *UserSignedTransactionDelete) Where(ps ...predicate.UserSignedTransaction) *UserSignedTransactionDelete {
	ustd.mutation.Where(ps...)
	return ustd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ustd *UserSignedTransactionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ustd.sqlExec, ustd.mutation, ustd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ustd *UserSignedTransactionDelete) ExecX(ctx context.Context) int {
	n, err := ustd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ustd *UserSignedTransactionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(usersignedtransaction.Table, sqlgraph.NewFieldSpec(usersignedtransaction.FieldID, field.TypeUUID))
	if ps := ustd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ustd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ustd.mutation.done = true
	return affected, err
}

// UserSignedTransactionDeleteOne is the builder for deleting a single UserSignedTransaction entity.
type UserSignedTransactionDeleteOne struct {
	ustd *UserSignedTransactionDelete
}

// Where appends a list predicates to the UserSignedTransactionDelete builder.
func (ustdo *UserSignedTransactionDeleteOne) Where(ps ...predicate.UserSignedTransaction) *UserSignedTransactionDeleteOne {
	ustdo.ustd.mutation.Where(ps...)
	return ustdo
}

// Exec executes the deletion query.
func (ustdo *UserSignedTransactionDeleteOne) Exec(ctx context.Context) error {
	n, err := ustdo.ustd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{usersignedtransaction.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ustdo *UserSignedTransactionDeleteOne) ExecX(ctx context.Context) {
	if err := ustdo.Exec(ctx); err != nil {
		panic(err)
	}
}
