// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignatureIntent int32

const (
	SignatureIntent_CREATION  SignatureIntent = 0
	SignatureIntent_TRANSFER  SignatureIntent = 1
	SignatureIntent_AGGREGATE SignatureIntent = 2
	SignatureIntent_REFRESH   SignatureIntent = 3
	SignatureIntent_EXTEND    SignatureIntent = 4
)

// Enum value maps for SignatureIntent.
var (
	SignatureIntent_name = map[int32]string{
		0: "CREATION",
		1: "TRANSFER",
		2: "AGGREGATE",
		3: "REFRESH",
		4: "EXTEND",
	}
	SignatureIntent_value = map[string]int32{
		"CREATION":  0,
		"TRANSFER":  1,
		"AGGREGATE": 2,
		"REFRESH":   3,
		"EXTEND":    4,
	}
)

func (x SignatureIntent) Enum() *SignatureIntent {
	p := new(SignatureIntent)
	*p = x
	return p
}

func (x SignatureIntent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignatureIntent) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (SignatureIntent) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x SignatureIntent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignatureIntent.Descriptor instead.
func (SignatureIntent) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

// A map from a string to a bytes. It's a workaround to have map arrays in proto.
type PackageMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packages      map[string][]byte      `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageMap) Reset() {
	*x = PackageMap{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageMap) ProtoMessage() {}

func (x *PackageMap) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageMap.ProtoReflect.Descriptor instead.
func (*PackageMap) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *PackageMap) GetPackages() map[string][]byte {
	if x != nil {
		return x.Packages
	}
	return nil
}

// A commitment for frost signing.
// It's a pair of public keys (points) in secp256k1 curve.
type SigningCommitment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The public key for hiding. 33 bytes.
	Hiding []byte `protobuf:"bytes,1,opt,name=hiding,proto3" json:"hiding,omitempty"`
	// The public key for binding. 33 bytes.
	Binding       []byte `protobuf:"bytes,2,opt,name=binding,proto3" json:"binding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningCommitment) Reset() {
	*x = SigningCommitment{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningCommitment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningCommitment) ProtoMessage() {}

func (x *SigningCommitment) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningCommitment.ProtoReflect.Descriptor instead.
func (*SigningCommitment) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *SigningCommitment) GetHiding() []byte {
	if x != nil {
		return x.Hiding
	}
	return nil
}

func (x *SigningCommitment) GetBinding() []byte {
	if x != nil {
		return x.Binding
	}
	return nil
}

type SigningResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SignatureShare []byte                 `protobuf:"bytes,1,opt,name=signature_share,json=signatureShare,proto3" json:"signature_share,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SigningResult) Reset() {
	*x = SigningResult{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningResult) ProtoMessage() {}

func (x *SigningResult) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningResult.ProtoReflect.Descriptor instead.
func (*SigningResult) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *SigningResult) GetSignatureShare() []byte {
	if x != nil {
		return x.SignatureShare
	}
	return nil
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x06common\"\x87\x01\n" +
	"\n" +
	"PackageMap\x12<\n" +
	"\bpackages\x18\x01 \x03(\v2 .common.PackageMap.PackagesEntryR\bpackages\x1a;\n" +
	"\rPackagesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"E\n" +
	"\x11SigningCommitment\x12\x16\n" +
	"\x06hiding\x18\x01 \x01(\fR\x06hiding\x12\x18\n" +
	"\abinding\x18\x02 \x01(\fR\abinding\"8\n" +
	"\rSigningResult\x12'\n" +
	"\x0fsignature_share\x18\x01 \x01(\fR\x0esignatureShare*U\n" +
	"\x0fSignatureIntent\x12\f\n" +
	"\bCREATION\x10\x00\x12\f\n" +
	"\bTRANSFER\x10\x01\x12\r\n" +
	"\tAGGREGATE\x10\x02\x12\v\n" +
	"\aREFRESH\x10\x03\x12\n" +
	"\n" +
	"\x06EXTEND\x10\x04B-Z+github.com/lightsparkdev/spark/proto/commonb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_common_proto_goTypes = []any{
	(SignatureIntent)(0),      // 0: common.SignatureIntent
	(*PackageMap)(nil),        // 1: common.PackageMap
	(*SigningCommitment)(nil), // 2: common.SigningCommitment
	(*SigningResult)(nil),     // 3: common.SigningResult
	nil,                       // 4: common.PackageMap.PackagesEntry
}
var file_common_proto_depIdxs = []int32{
	4, // 0: common.PackageMap.packages:type_name -> common.PackageMap.PackagesEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
