-- Create "token_transactions" table
CREATE TABLE "token_transactions" ("id" uuid NOT NULL, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "partial_token_transaction_hash" bytea NOT NULL, "finalized_token_transaction_hash" bytea NOT NULL, "operator_signature" bytea NULL, "status" character varying NULL, "token_transaction_mint" uuid NULL, PRIMARY KEY ("id"), CONSTRAINT "token_transactions_token_mints_mint" FOREIGN KEY ("token_transaction_mint") REFERENCES "token_mints" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create index "token_transactions_finalized_token_transaction_hash_key" to table: "token_transactions"
CREATE UNIQUE INDEX "token_transactions_finalized_token_transaction_hash_key" ON "token_transactions" ("finalized_token_transaction_hash");
-- Create index "token_transactions_operator_signature_key" to table: "token_transactions"
CREATE UNIQUE INDEX "token_transactions_operator_signature_key" ON "token_transactions" ("operator_signature");
-- Create index "tokentransaction_finalized_token_transaction_hash" to table: "token_transactions"
CREATE INDEX "tokentransaction_finalized_token_transaction_hash" ON "token_transactions" ("finalized_token_transaction_hash");
-- Create "token_outputs" table
CREATE TABLE "token_outputs" ("id" uuid NOT NULL, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "status" character varying NOT NULL, "owner_public_key" bytea NOT NULL, "withdraw_bond_sats" bigint NOT NULL, "withdraw_relative_block_locktime" bigint NOT NULL, "withdraw_revocation_commitment" bytea NOT NULL, "token_public_key" bytea NOT NULL, "token_amount" bytea NOT NULL, "created_transaction_output_vout" integer NOT NULL, "spent_ownership_signature" bytea NULL, "spent_operator_specific_ownership_signature" bytea NULL, "spent_transaction_input_vout" integer NULL, "spent_revocation_secret" bytea NULL, "confirmed_withdraw_block_hash" bytea NULL, "network" character varying NULL, "token_output_revocation_keyshare" uuid NOT NULL, "token_output_output_created_token_transaction" uuid NULL, "token_output_output_spent_token_transaction" uuid NULL, PRIMARY KEY ("id"), CONSTRAINT "token_outputs_signing_keyshares_revocation_keyshare" FOREIGN KEY ("token_output_revocation_keyshare") REFERENCES "signing_keyshares" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "token_outputs_token_transactio_d0380012988c8a57eb9f0fa7b88ce6d3" FOREIGN KEY ("token_output_output_created_token_transaction") REFERENCES "token_transactions" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT "token_outputs_token_transactions_output_spent_token_transaction" FOREIGN KEY ("token_output_output_spent_token_transaction") REFERENCES "token_transactions" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create index "tokenoutput_confirmed_withdraw_block_hash" to table: "token_outputs"
CREATE INDEX "tokenoutput_confirmed_withdraw_block_hash" ON "token_outputs" ("confirmed_withdraw_block_hash");
-- Create index "tokenoutput_owner_public_key_token_public_key" to table: "token_outputs"
CREATE INDEX "tokenoutput_owner_public_key_token_public_key" ON "token_outputs" ("owner_public_key", "token_public_key");
