// Code generated by ent, DO NOT EDIT.

package tokenleaf

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/so/ent/predicate"
	"github.com/lightsparkdev/spark/so/ent/schema"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldEQ(FieldUpdateTime, v))
}

// OwnerPublicKey applies equality check predicate on the "owner_public_key" field. It's identical to OwnerPublicKeyEQ.
func OwnerPublicKey(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldEQ(FieldOwnerPublicKey, v))
}

// WithdrawBondSats applies equality check predicate on the "withdraw_bond_sats" field. It's identical to WithdrawBondSatsEQ.
func WithdrawBondSats(v uint64) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldEQ(FieldWithdrawBondSats, v))
}

// WithdrawRelativeBlockLocktime applies equality check predicate on the "withdraw_relative_block_locktime" field. It's identical to WithdrawRelativeBlockLocktimeEQ.
func WithdrawRelativeBlockLocktime(v uint64) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldEQ(FieldWithdrawRelativeBlockLocktime, v))
}

// WithdrawRevocationPublicKey applies equality check predicate on the "withdraw_revocation_public_key" field. It's identical to WithdrawRevocationPublicKeyEQ.
func WithdrawRevocationPublicKey(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldEQ(FieldWithdrawRevocationPublicKey, v))
}

// TokenPublicKey applies equality check predicate on the "token_public_key" field. It's identical to TokenPublicKeyEQ.
func TokenPublicKey(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldEQ(FieldTokenPublicKey, v))
}

// TokenAmount applies equality check predicate on the "token_amount" field. It's identical to TokenAmountEQ.
func TokenAmount(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldEQ(FieldTokenAmount, v))
}

// LeafCreatedTransactionOutputVout applies equality check predicate on the "leaf_created_transaction_output_vout" field. It's identical to LeafCreatedTransactionOutputVoutEQ.
func LeafCreatedTransactionOutputVout(v int32) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldEQ(FieldLeafCreatedTransactionOutputVout, v))
}

// LeafSpentOwnershipSignature applies equality check predicate on the "leaf_spent_ownership_signature" field. It's identical to LeafSpentOwnershipSignatureEQ.
func LeafSpentOwnershipSignature(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldEQ(FieldLeafSpentOwnershipSignature, v))
}

// LeafSpentOperatorSpecificOwnershipSignature applies equality check predicate on the "leaf_spent_operator_specific_ownership_signature" field. It's identical to LeafSpentOperatorSpecificOwnershipSignatureEQ.
func LeafSpentOperatorSpecificOwnershipSignature(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldEQ(FieldLeafSpentOperatorSpecificOwnershipSignature, v))
}

// LeafSpentTransactionInputVout applies equality check predicate on the "leaf_spent_transaction_input_vout" field. It's identical to LeafSpentTransactionInputVoutEQ.
func LeafSpentTransactionInputVout(v int32) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldEQ(FieldLeafSpentTransactionInputVout, v))
}

// LeafSpentRevocationPrivateKey applies equality check predicate on the "leaf_spent_revocation_private_key" field. It's identical to LeafSpentRevocationPrivateKeyEQ.
func LeafSpentRevocationPrivateKey(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldEQ(FieldLeafSpentRevocationPrivateKey, v))
}

// ConfirmedWithdrawBlockHash applies equality check predicate on the "confirmed_withdraw_block_hash" field. It's identical to ConfirmedWithdrawBlockHashEQ.
func ConfirmedWithdrawBlockHash(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldEQ(FieldConfirmedWithdrawBlockHash, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldLTE(FieldUpdateTime, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v schema.TokenLeafStatus) predicate.TokenLeaf {
	vc := v
	return predicate.TokenLeaf(sql.FieldEQ(FieldStatus, vc))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v schema.TokenLeafStatus) predicate.TokenLeaf {
	vc := v
	return predicate.TokenLeaf(sql.FieldNEQ(FieldStatus, vc))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...schema.TokenLeafStatus) predicate.TokenLeaf {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TokenLeaf(sql.FieldIn(FieldStatus, v...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...schema.TokenLeafStatus) predicate.TokenLeaf {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TokenLeaf(sql.FieldNotIn(FieldStatus, v...))
}

// OwnerPublicKeyEQ applies the EQ predicate on the "owner_public_key" field.
func OwnerPublicKeyEQ(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldEQ(FieldOwnerPublicKey, v))
}

// OwnerPublicKeyNEQ applies the NEQ predicate on the "owner_public_key" field.
func OwnerPublicKeyNEQ(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldNEQ(FieldOwnerPublicKey, v))
}

// OwnerPublicKeyIn applies the In predicate on the "owner_public_key" field.
func OwnerPublicKeyIn(vs ...[]byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldIn(FieldOwnerPublicKey, vs...))
}

// OwnerPublicKeyNotIn applies the NotIn predicate on the "owner_public_key" field.
func OwnerPublicKeyNotIn(vs ...[]byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldNotIn(FieldOwnerPublicKey, vs...))
}

// OwnerPublicKeyGT applies the GT predicate on the "owner_public_key" field.
func OwnerPublicKeyGT(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldGT(FieldOwnerPublicKey, v))
}

// OwnerPublicKeyGTE applies the GTE predicate on the "owner_public_key" field.
func OwnerPublicKeyGTE(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldGTE(FieldOwnerPublicKey, v))
}

// OwnerPublicKeyLT applies the LT predicate on the "owner_public_key" field.
func OwnerPublicKeyLT(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldLT(FieldOwnerPublicKey, v))
}

// OwnerPublicKeyLTE applies the LTE predicate on the "owner_public_key" field.
func OwnerPublicKeyLTE(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldLTE(FieldOwnerPublicKey, v))
}

// WithdrawBondSatsEQ applies the EQ predicate on the "withdraw_bond_sats" field.
func WithdrawBondSatsEQ(v uint64) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldEQ(FieldWithdrawBondSats, v))
}

// WithdrawBondSatsNEQ applies the NEQ predicate on the "withdraw_bond_sats" field.
func WithdrawBondSatsNEQ(v uint64) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldNEQ(FieldWithdrawBondSats, v))
}

// WithdrawBondSatsIn applies the In predicate on the "withdraw_bond_sats" field.
func WithdrawBondSatsIn(vs ...uint64) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldIn(FieldWithdrawBondSats, vs...))
}

// WithdrawBondSatsNotIn applies the NotIn predicate on the "withdraw_bond_sats" field.
func WithdrawBondSatsNotIn(vs ...uint64) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldNotIn(FieldWithdrawBondSats, vs...))
}

// WithdrawBondSatsGT applies the GT predicate on the "withdraw_bond_sats" field.
func WithdrawBondSatsGT(v uint64) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldGT(FieldWithdrawBondSats, v))
}

// WithdrawBondSatsGTE applies the GTE predicate on the "withdraw_bond_sats" field.
func WithdrawBondSatsGTE(v uint64) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldGTE(FieldWithdrawBondSats, v))
}

// WithdrawBondSatsLT applies the LT predicate on the "withdraw_bond_sats" field.
func WithdrawBondSatsLT(v uint64) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldLT(FieldWithdrawBondSats, v))
}

// WithdrawBondSatsLTE applies the LTE predicate on the "withdraw_bond_sats" field.
func WithdrawBondSatsLTE(v uint64) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldLTE(FieldWithdrawBondSats, v))
}

// WithdrawRelativeBlockLocktimeEQ applies the EQ predicate on the "withdraw_relative_block_locktime" field.
func WithdrawRelativeBlockLocktimeEQ(v uint64) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldEQ(FieldWithdrawRelativeBlockLocktime, v))
}

// WithdrawRelativeBlockLocktimeNEQ applies the NEQ predicate on the "withdraw_relative_block_locktime" field.
func WithdrawRelativeBlockLocktimeNEQ(v uint64) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldNEQ(FieldWithdrawRelativeBlockLocktime, v))
}

// WithdrawRelativeBlockLocktimeIn applies the In predicate on the "withdraw_relative_block_locktime" field.
func WithdrawRelativeBlockLocktimeIn(vs ...uint64) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldIn(FieldWithdrawRelativeBlockLocktime, vs...))
}

// WithdrawRelativeBlockLocktimeNotIn applies the NotIn predicate on the "withdraw_relative_block_locktime" field.
func WithdrawRelativeBlockLocktimeNotIn(vs ...uint64) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldNotIn(FieldWithdrawRelativeBlockLocktime, vs...))
}

// WithdrawRelativeBlockLocktimeGT applies the GT predicate on the "withdraw_relative_block_locktime" field.
func WithdrawRelativeBlockLocktimeGT(v uint64) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldGT(FieldWithdrawRelativeBlockLocktime, v))
}

// WithdrawRelativeBlockLocktimeGTE applies the GTE predicate on the "withdraw_relative_block_locktime" field.
func WithdrawRelativeBlockLocktimeGTE(v uint64) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldGTE(FieldWithdrawRelativeBlockLocktime, v))
}

// WithdrawRelativeBlockLocktimeLT applies the LT predicate on the "withdraw_relative_block_locktime" field.
func WithdrawRelativeBlockLocktimeLT(v uint64) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldLT(FieldWithdrawRelativeBlockLocktime, v))
}

// WithdrawRelativeBlockLocktimeLTE applies the LTE predicate on the "withdraw_relative_block_locktime" field.
func WithdrawRelativeBlockLocktimeLTE(v uint64) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldLTE(FieldWithdrawRelativeBlockLocktime, v))
}

// WithdrawRevocationPublicKeyEQ applies the EQ predicate on the "withdraw_revocation_public_key" field.
func WithdrawRevocationPublicKeyEQ(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldEQ(FieldWithdrawRevocationPublicKey, v))
}

// WithdrawRevocationPublicKeyNEQ applies the NEQ predicate on the "withdraw_revocation_public_key" field.
func WithdrawRevocationPublicKeyNEQ(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldNEQ(FieldWithdrawRevocationPublicKey, v))
}

// WithdrawRevocationPublicKeyIn applies the In predicate on the "withdraw_revocation_public_key" field.
func WithdrawRevocationPublicKeyIn(vs ...[]byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldIn(FieldWithdrawRevocationPublicKey, vs...))
}

// WithdrawRevocationPublicKeyNotIn applies the NotIn predicate on the "withdraw_revocation_public_key" field.
func WithdrawRevocationPublicKeyNotIn(vs ...[]byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldNotIn(FieldWithdrawRevocationPublicKey, vs...))
}

// WithdrawRevocationPublicKeyGT applies the GT predicate on the "withdraw_revocation_public_key" field.
func WithdrawRevocationPublicKeyGT(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldGT(FieldWithdrawRevocationPublicKey, v))
}

// WithdrawRevocationPublicKeyGTE applies the GTE predicate on the "withdraw_revocation_public_key" field.
func WithdrawRevocationPublicKeyGTE(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldGTE(FieldWithdrawRevocationPublicKey, v))
}

// WithdrawRevocationPublicKeyLT applies the LT predicate on the "withdraw_revocation_public_key" field.
func WithdrawRevocationPublicKeyLT(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldLT(FieldWithdrawRevocationPublicKey, v))
}

// WithdrawRevocationPublicKeyLTE applies the LTE predicate on the "withdraw_revocation_public_key" field.
func WithdrawRevocationPublicKeyLTE(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldLTE(FieldWithdrawRevocationPublicKey, v))
}

// TokenPublicKeyEQ applies the EQ predicate on the "token_public_key" field.
func TokenPublicKeyEQ(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldEQ(FieldTokenPublicKey, v))
}

// TokenPublicKeyNEQ applies the NEQ predicate on the "token_public_key" field.
func TokenPublicKeyNEQ(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldNEQ(FieldTokenPublicKey, v))
}

// TokenPublicKeyIn applies the In predicate on the "token_public_key" field.
func TokenPublicKeyIn(vs ...[]byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldIn(FieldTokenPublicKey, vs...))
}

// TokenPublicKeyNotIn applies the NotIn predicate on the "token_public_key" field.
func TokenPublicKeyNotIn(vs ...[]byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldNotIn(FieldTokenPublicKey, vs...))
}

// TokenPublicKeyGT applies the GT predicate on the "token_public_key" field.
func TokenPublicKeyGT(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldGT(FieldTokenPublicKey, v))
}

// TokenPublicKeyGTE applies the GTE predicate on the "token_public_key" field.
func TokenPublicKeyGTE(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldGTE(FieldTokenPublicKey, v))
}

// TokenPublicKeyLT applies the LT predicate on the "token_public_key" field.
func TokenPublicKeyLT(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldLT(FieldTokenPublicKey, v))
}

// TokenPublicKeyLTE applies the LTE predicate on the "token_public_key" field.
func TokenPublicKeyLTE(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldLTE(FieldTokenPublicKey, v))
}

// TokenAmountEQ applies the EQ predicate on the "token_amount" field.
func TokenAmountEQ(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldEQ(FieldTokenAmount, v))
}

// TokenAmountNEQ applies the NEQ predicate on the "token_amount" field.
func TokenAmountNEQ(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldNEQ(FieldTokenAmount, v))
}

// TokenAmountIn applies the In predicate on the "token_amount" field.
func TokenAmountIn(vs ...[]byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldIn(FieldTokenAmount, vs...))
}

// TokenAmountNotIn applies the NotIn predicate on the "token_amount" field.
func TokenAmountNotIn(vs ...[]byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldNotIn(FieldTokenAmount, vs...))
}

// TokenAmountGT applies the GT predicate on the "token_amount" field.
func TokenAmountGT(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldGT(FieldTokenAmount, v))
}

// TokenAmountGTE applies the GTE predicate on the "token_amount" field.
func TokenAmountGTE(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldGTE(FieldTokenAmount, v))
}

// TokenAmountLT applies the LT predicate on the "token_amount" field.
func TokenAmountLT(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldLT(FieldTokenAmount, v))
}

// TokenAmountLTE applies the LTE predicate on the "token_amount" field.
func TokenAmountLTE(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldLTE(FieldTokenAmount, v))
}

// LeafCreatedTransactionOutputVoutEQ applies the EQ predicate on the "leaf_created_transaction_output_vout" field.
func LeafCreatedTransactionOutputVoutEQ(v int32) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldEQ(FieldLeafCreatedTransactionOutputVout, v))
}

// LeafCreatedTransactionOutputVoutNEQ applies the NEQ predicate on the "leaf_created_transaction_output_vout" field.
func LeafCreatedTransactionOutputVoutNEQ(v int32) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldNEQ(FieldLeafCreatedTransactionOutputVout, v))
}

// LeafCreatedTransactionOutputVoutIn applies the In predicate on the "leaf_created_transaction_output_vout" field.
func LeafCreatedTransactionOutputVoutIn(vs ...int32) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldIn(FieldLeafCreatedTransactionOutputVout, vs...))
}

// LeafCreatedTransactionOutputVoutNotIn applies the NotIn predicate on the "leaf_created_transaction_output_vout" field.
func LeafCreatedTransactionOutputVoutNotIn(vs ...int32) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldNotIn(FieldLeafCreatedTransactionOutputVout, vs...))
}

// LeafCreatedTransactionOutputVoutGT applies the GT predicate on the "leaf_created_transaction_output_vout" field.
func LeafCreatedTransactionOutputVoutGT(v int32) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldGT(FieldLeafCreatedTransactionOutputVout, v))
}

// LeafCreatedTransactionOutputVoutGTE applies the GTE predicate on the "leaf_created_transaction_output_vout" field.
func LeafCreatedTransactionOutputVoutGTE(v int32) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldGTE(FieldLeafCreatedTransactionOutputVout, v))
}

// LeafCreatedTransactionOutputVoutLT applies the LT predicate on the "leaf_created_transaction_output_vout" field.
func LeafCreatedTransactionOutputVoutLT(v int32) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldLT(FieldLeafCreatedTransactionOutputVout, v))
}

// LeafCreatedTransactionOutputVoutLTE applies the LTE predicate on the "leaf_created_transaction_output_vout" field.
func LeafCreatedTransactionOutputVoutLTE(v int32) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldLTE(FieldLeafCreatedTransactionOutputVout, v))
}

// LeafSpentOwnershipSignatureEQ applies the EQ predicate on the "leaf_spent_ownership_signature" field.
func LeafSpentOwnershipSignatureEQ(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldEQ(FieldLeafSpentOwnershipSignature, v))
}

// LeafSpentOwnershipSignatureNEQ applies the NEQ predicate on the "leaf_spent_ownership_signature" field.
func LeafSpentOwnershipSignatureNEQ(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldNEQ(FieldLeafSpentOwnershipSignature, v))
}

// LeafSpentOwnershipSignatureIn applies the In predicate on the "leaf_spent_ownership_signature" field.
func LeafSpentOwnershipSignatureIn(vs ...[]byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldIn(FieldLeafSpentOwnershipSignature, vs...))
}

// LeafSpentOwnershipSignatureNotIn applies the NotIn predicate on the "leaf_spent_ownership_signature" field.
func LeafSpentOwnershipSignatureNotIn(vs ...[]byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldNotIn(FieldLeafSpentOwnershipSignature, vs...))
}

// LeafSpentOwnershipSignatureGT applies the GT predicate on the "leaf_spent_ownership_signature" field.
func LeafSpentOwnershipSignatureGT(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldGT(FieldLeafSpentOwnershipSignature, v))
}

// LeafSpentOwnershipSignatureGTE applies the GTE predicate on the "leaf_spent_ownership_signature" field.
func LeafSpentOwnershipSignatureGTE(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldGTE(FieldLeafSpentOwnershipSignature, v))
}

// LeafSpentOwnershipSignatureLT applies the LT predicate on the "leaf_spent_ownership_signature" field.
func LeafSpentOwnershipSignatureLT(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldLT(FieldLeafSpentOwnershipSignature, v))
}

// LeafSpentOwnershipSignatureLTE applies the LTE predicate on the "leaf_spent_ownership_signature" field.
func LeafSpentOwnershipSignatureLTE(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldLTE(FieldLeafSpentOwnershipSignature, v))
}

// LeafSpentOwnershipSignatureIsNil applies the IsNil predicate on the "leaf_spent_ownership_signature" field.
func LeafSpentOwnershipSignatureIsNil() predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldIsNull(FieldLeafSpentOwnershipSignature))
}

// LeafSpentOwnershipSignatureNotNil applies the NotNil predicate on the "leaf_spent_ownership_signature" field.
func LeafSpentOwnershipSignatureNotNil() predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldNotNull(FieldLeafSpentOwnershipSignature))
}

// LeafSpentOperatorSpecificOwnershipSignatureEQ applies the EQ predicate on the "leaf_spent_operator_specific_ownership_signature" field.
func LeafSpentOperatorSpecificOwnershipSignatureEQ(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldEQ(FieldLeafSpentOperatorSpecificOwnershipSignature, v))
}

// LeafSpentOperatorSpecificOwnershipSignatureNEQ applies the NEQ predicate on the "leaf_spent_operator_specific_ownership_signature" field.
func LeafSpentOperatorSpecificOwnershipSignatureNEQ(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldNEQ(FieldLeafSpentOperatorSpecificOwnershipSignature, v))
}

// LeafSpentOperatorSpecificOwnershipSignatureIn applies the In predicate on the "leaf_spent_operator_specific_ownership_signature" field.
func LeafSpentOperatorSpecificOwnershipSignatureIn(vs ...[]byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldIn(FieldLeafSpentOperatorSpecificOwnershipSignature, vs...))
}

// LeafSpentOperatorSpecificOwnershipSignatureNotIn applies the NotIn predicate on the "leaf_spent_operator_specific_ownership_signature" field.
func LeafSpentOperatorSpecificOwnershipSignatureNotIn(vs ...[]byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldNotIn(FieldLeafSpentOperatorSpecificOwnershipSignature, vs...))
}

// LeafSpentOperatorSpecificOwnershipSignatureGT applies the GT predicate on the "leaf_spent_operator_specific_ownership_signature" field.
func LeafSpentOperatorSpecificOwnershipSignatureGT(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldGT(FieldLeafSpentOperatorSpecificOwnershipSignature, v))
}

// LeafSpentOperatorSpecificOwnershipSignatureGTE applies the GTE predicate on the "leaf_spent_operator_specific_ownership_signature" field.
func LeafSpentOperatorSpecificOwnershipSignatureGTE(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldGTE(FieldLeafSpentOperatorSpecificOwnershipSignature, v))
}

// LeafSpentOperatorSpecificOwnershipSignatureLT applies the LT predicate on the "leaf_spent_operator_specific_ownership_signature" field.
func LeafSpentOperatorSpecificOwnershipSignatureLT(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldLT(FieldLeafSpentOperatorSpecificOwnershipSignature, v))
}

// LeafSpentOperatorSpecificOwnershipSignatureLTE applies the LTE predicate on the "leaf_spent_operator_specific_ownership_signature" field.
func LeafSpentOperatorSpecificOwnershipSignatureLTE(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldLTE(FieldLeafSpentOperatorSpecificOwnershipSignature, v))
}

// LeafSpentOperatorSpecificOwnershipSignatureIsNil applies the IsNil predicate on the "leaf_spent_operator_specific_ownership_signature" field.
func LeafSpentOperatorSpecificOwnershipSignatureIsNil() predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldIsNull(FieldLeafSpentOperatorSpecificOwnershipSignature))
}

// LeafSpentOperatorSpecificOwnershipSignatureNotNil applies the NotNil predicate on the "leaf_spent_operator_specific_ownership_signature" field.
func LeafSpentOperatorSpecificOwnershipSignatureNotNil() predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldNotNull(FieldLeafSpentOperatorSpecificOwnershipSignature))
}

// LeafSpentTransactionInputVoutEQ applies the EQ predicate on the "leaf_spent_transaction_input_vout" field.
func LeafSpentTransactionInputVoutEQ(v int32) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldEQ(FieldLeafSpentTransactionInputVout, v))
}

// LeafSpentTransactionInputVoutNEQ applies the NEQ predicate on the "leaf_spent_transaction_input_vout" field.
func LeafSpentTransactionInputVoutNEQ(v int32) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldNEQ(FieldLeafSpentTransactionInputVout, v))
}

// LeafSpentTransactionInputVoutIn applies the In predicate on the "leaf_spent_transaction_input_vout" field.
func LeafSpentTransactionInputVoutIn(vs ...int32) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldIn(FieldLeafSpentTransactionInputVout, vs...))
}

// LeafSpentTransactionInputVoutNotIn applies the NotIn predicate on the "leaf_spent_transaction_input_vout" field.
func LeafSpentTransactionInputVoutNotIn(vs ...int32) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldNotIn(FieldLeafSpentTransactionInputVout, vs...))
}

// LeafSpentTransactionInputVoutGT applies the GT predicate on the "leaf_spent_transaction_input_vout" field.
func LeafSpentTransactionInputVoutGT(v int32) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldGT(FieldLeafSpentTransactionInputVout, v))
}

// LeafSpentTransactionInputVoutGTE applies the GTE predicate on the "leaf_spent_transaction_input_vout" field.
func LeafSpentTransactionInputVoutGTE(v int32) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldGTE(FieldLeafSpentTransactionInputVout, v))
}

// LeafSpentTransactionInputVoutLT applies the LT predicate on the "leaf_spent_transaction_input_vout" field.
func LeafSpentTransactionInputVoutLT(v int32) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldLT(FieldLeafSpentTransactionInputVout, v))
}

// LeafSpentTransactionInputVoutLTE applies the LTE predicate on the "leaf_spent_transaction_input_vout" field.
func LeafSpentTransactionInputVoutLTE(v int32) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldLTE(FieldLeafSpentTransactionInputVout, v))
}

// LeafSpentTransactionInputVoutIsNil applies the IsNil predicate on the "leaf_spent_transaction_input_vout" field.
func LeafSpentTransactionInputVoutIsNil() predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldIsNull(FieldLeafSpentTransactionInputVout))
}

// LeafSpentTransactionInputVoutNotNil applies the NotNil predicate on the "leaf_spent_transaction_input_vout" field.
func LeafSpentTransactionInputVoutNotNil() predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldNotNull(FieldLeafSpentTransactionInputVout))
}

// LeafSpentRevocationPrivateKeyEQ applies the EQ predicate on the "leaf_spent_revocation_private_key" field.
func LeafSpentRevocationPrivateKeyEQ(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldEQ(FieldLeafSpentRevocationPrivateKey, v))
}

// LeafSpentRevocationPrivateKeyNEQ applies the NEQ predicate on the "leaf_spent_revocation_private_key" field.
func LeafSpentRevocationPrivateKeyNEQ(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldNEQ(FieldLeafSpentRevocationPrivateKey, v))
}

// LeafSpentRevocationPrivateKeyIn applies the In predicate on the "leaf_spent_revocation_private_key" field.
func LeafSpentRevocationPrivateKeyIn(vs ...[]byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldIn(FieldLeafSpentRevocationPrivateKey, vs...))
}

// LeafSpentRevocationPrivateKeyNotIn applies the NotIn predicate on the "leaf_spent_revocation_private_key" field.
func LeafSpentRevocationPrivateKeyNotIn(vs ...[]byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldNotIn(FieldLeafSpentRevocationPrivateKey, vs...))
}

// LeafSpentRevocationPrivateKeyGT applies the GT predicate on the "leaf_spent_revocation_private_key" field.
func LeafSpentRevocationPrivateKeyGT(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldGT(FieldLeafSpentRevocationPrivateKey, v))
}

// LeafSpentRevocationPrivateKeyGTE applies the GTE predicate on the "leaf_spent_revocation_private_key" field.
func LeafSpentRevocationPrivateKeyGTE(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldGTE(FieldLeafSpentRevocationPrivateKey, v))
}

// LeafSpentRevocationPrivateKeyLT applies the LT predicate on the "leaf_spent_revocation_private_key" field.
func LeafSpentRevocationPrivateKeyLT(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldLT(FieldLeafSpentRevocationPrivateKey, v))
}

// LeafSpentRevocationPrivateKeyLTE applies the LTE predicate on the "leaf_spent_revocation_private_key" field.
func LeafSpentRevocationPrivateKeyLTE(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldLTE(FieldLeafSpentRevocationPrivateKey, v))
}

// LeafSpentRevocationPrivateKeyIsNil applies the IsNil predicate on the "leaf_spent_revocation_private_key" field.
func LeafSpentRevocationPrivateKeyIsNil() predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldIsNull(FieldLeafSpentRevocationPrivateKey))
}

// LeafSpentRevocationPrivateKeyNotNil applies the NotNil predicate on the "leaf_spent_revocation_private_key" field.
func LeafSpentRevocationPrivateKeyNotNil() predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldNotNull(FieldLeafSpentRevocationPrivateKey))
}

// ConfirmedWithdrawBlockHashEQ applies the EQ predicate on the "confirmed_withdraw_block_hash" field.
func ConfirmedWithdrawBlockHashEQ(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldEQ(FieldConfirmedWithdrawBlockHash, v))
}

// ConfirmedWithdrawBlockHashNEQ applies the NEQ predicate on the "confirmed_withdraw_block_hash" field.
func ConfirmedWithdrawBlockHashNEQ(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldNEQ(FieldConfirmedWithdrawBlockHash, v))
}

// ConfirmedWithdrawBlockHashIn applies the In predicate on the "confirmed_withdraw_block_hash" field.
func ConfirmedWithdrawBlockHashIn(vs ...[]byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldIn(FieldConfirmedWithdrawBlockHash, vs...))
}

// ConfirmedWithdrawBlockHashNotIn applies the NotIn predicate on the "confirmed_withdraw_block_hash" field.
func ConfirmedWithdrawBlockHashNotIn(vs ...[]byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldNotIn(FieldConfirmedWithdrawBlockHash, vs...))
}

// ConfirmedWithdrawBlockHashGT applies the GT predicate on the "confirmed_withdraw_block_hash" field.
func ConfirmedWithdrawBlockHashGT(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldGT(FieldConfirmedWithdrawBlockHash, v))
}

// ConfirmedWithdrawBlockHashGTE applies the GTE predicate on the "confirmed_withdraw_block_hash" field.
func ConfirmedWithdrawBlockHashGTE(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldGTE(FieldConfirmedWithdrawBlockHash, v))
}

// ConfirmedWithdrawBlockHashLT applies the LT predicate on the "confirmed_withdraw_block_hash" field.
func ConfirmedWithdrawBlockHashLT(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldLT(FieldConfirmedWithdrawBlockHash, v))
}

// ConfirmedWithdrawBlockHashLTE applies the LTE predicate on the "confirmed_withdraw_block_hash" field.
func ConfirmedWithdrawBlockHashLTE(v []byte) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldLTE(FieldConfirmedWithdrawBlockHash, v))
}

// ConfirmedWithdrawBlockHashIsNil applies the IsNil predicate on the "confirmed_withdraw_block_hash" field.
func ConfirmedWithdrawBlockHashIsNil() predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldIsNull(FieldConfirmedWithdrawBlockHash))
}

// ConfirmedWithdrawBlockHashNotNil applies the NotNil predicate on the "confirmed_withdraw_block_hash" field.
func ConfirmedWithdrawBlockHashNotNil() predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldNotNull(FieldConfirmedWithdrawBlockHash))
}

// NetworkEQ applies the EQ predicate on the "network" field.
func NetworkEQ(v schema.Network) predicate.TokenLeaf {
	vc := v
	return predicate.TokenLeaf(sql.FieldEQ(FieldNetwork, vc))
}

// NetworkNEQ applies the NEQ predicate on the "network" field.
func NetworkNEQ(v schema.Network) predicate.TokenLeaf {
	vc := v
	return predicate.TokenLeaf(sql.FieldNEQ(FieldNetwork, vc))
}

// NetworkIn applies the In predicate on the "network" field.
func NetworkIn(vs ...schema.Network) predicate.TokenLeaf {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TokenLeaf(sql.FieldIn(FieldNetwork, v...))
}

// NetworkNotIn applies the NotIn predicate on the "network" field.
func NetworkNotIn(vs ...schema.Network) predicate.TokenLeaf {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TokenLeaf(sql.FieldNotIn(FieldNetwork, v...))
}

// NetworkIsNil applies the IsNil predicate on the "network" field.
func NetworkIsNil() predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldIsNull(FieldNetwork))
}

// NetworkNotNil applies the NotNil predicate on the "network" field.
func NetworkNotNil() predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.FieldNotNull(FieldNetwork))
}

// HasRevocationKeyshare applies the HasEdge predicate on the "revocation_keyshare" edge.
func HasRevocationKeyshare() predicate.TokenLeaf {
	return predicate.TokenLeaf(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, RevocationKeyshareTable, RevocationKeyshareColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRevocationKeyshareWith applies the HasEdge predicate on the "revocation_keyshare" edge with a given conditions (other predicates).
func HasRevocationKeyshareWith(preds ...predicate.SigningKeyshare) predicate.TokenLeaf {
	return predicate.TokenLeaf(func(s *sql.Selector) {
		step := newRevocationKeyshareStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLeafCreatedTokenTransactionReceipt applies the HasEdge predicate on the "leaf_created_token_transaction_receipt" edge.
func HasLeafCreatedTokenTransactionReceipt() predicate.TokenLeaf {
	return predicate.TokenLeaf(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, LeafCreatedTokenTransactionReceiptTable, LeafCreatedTokenTransactionReceiptColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLeafCreatedTokenTransactionReceiptWith applies the HasEdge predicate on the "leaf_created_token_transaction_receipt" edge with a given conditions (other predicates).
func HasLeafCreatedTokenTransactionReceiptWith(preds ...predicate.TokenTransactionReceipt) predicate.TokenLeaf {
	return predicate.TokenLeaf(func(s *sql.Selector) {
		step := newLeafCreatedTokenTransactionReceiptStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLeafSpentTokenTransactionReceipt applies the HasEdge predicate on the "leaf_spent_token_transaction_receipt" edge.
func HasLeafSpentTokenTransactionReceipt() predicate.TokenLeaf {
	return predicate.TokenLeaf(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, LeafSpentTokenTransactionReceiptTable, LeafSpentTokenTransactionReceiptColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLeafSpentTokenTransactionReceiptWith applies the HasEdge predicate on the "leaf_spent_token_transaction_receipt" edge with a given conditions (other predicates).
func HasLeafSpentTokenTransactionReceiptWith(preds ...predicate.TokenTransactionReceipt) predicate.TokenLeaf {
	return predicate.TokenLeaf(func(s *sql.Selector) {
		step := newLeafSpentTokenTransactionReceiptStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TokenLeaf) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TokenLeaf) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TokenLeaf) predicate.TokenLeaf {
	return predicate.TokenLeaf(sql.NotPredicates(p))
}
