// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v5.29.3
// source: rpc/v1/types.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Timestamp } from "../../google/protobuf/timestamp.js";

export const protobufPackage = "rpc.v1";

export enum Layer {
  L1 = 0,
  SPARK = 1,
  UNRECOGNIZED = -1,
}

export function layerFromJSON(object: any): Layer {
  switch (object) {
    case 0:
    case "L1":
      return Layer.L1;
    case 1:
    case "SPARK":
      return Layer.SPARK;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Layer.UNRECOGNIZED;
  }
}

export function layerToJSON(object: Layer): string {
  switch (object) {
    case Layer.L1:
      return "L1";
    case Layer.SPARK:
      return "SPARK";
    case Layer.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum OperationType {
  /** USER_TRANSFER - User operations */
  USER_TRANSFER = 0,
  USER_BURN = 1,
  /** ISSUER_ANNOUNCE - Issuer operations */
  ISSUER_ANNOUNCE = 2,
  ISSUER_MINT = 3,
  ISSUER_TRANSFER = 4,
  ISSUER_FREEZE = 5,
  ISSUER_UNFREEZE = 6,
  ISSUER_BURN = 7,
  UNRECOGNIZED = -1,
}

export function operationTypeFromJSON(object: any): OperationType {
  switch (object) {
    case 0:
    case "USER_TRANSFER":
      return OperationType.USER_TRANSFER;
    case 1:
    case "USER_BURN":
      return OperationType.USER_BURN;
    case 2:
    case "ISSUER_ANNOUNCE":
      return OperationType.ISSUER_ANNOUNCE;
    case 3:
    case "ISSUER_MINT":
      return OperationType.ISSUER_MINT;
    case 4:
    case "ISSUER_TRANSFER":
      return OperationType.ISSUER_TRANSFER;
    case 5:
    case "ISSUER_FREEZE":
      return OperationType.ISSUER_FREEZE;
    case 6:
    case "ISSUER_UNFREEZE":
      return OperationType.ISSUER_UNFREEZE;
    case 7:
    case "ISSUER_BURN":
      return OperationType.ISSUER_BURN;
    case -1:
    case "UNRECOGNIZED":
    default:
      return OperationType.UNRECOGNIZED;
  }
}

export function operationTypeToJSON(object: OperationType): string {
  switch (object) {
    case OperationType.USER_TRANSFER:
      return "USER_TRANSFER";
    case OperationType.USER_BURN:
      return "USER_BURN";
    case OperationType.ISSUER_ANNOUNCE:
      return "ISSUER_ANNOUNCE";
    case OperationType.ISSUER_MINT:
      return "ISSUER_MINT";
    case OperationType.ISSUER_TRANSFER:
      return "ISSUER_TRANSFER";
    case OperationType.ISSUER_FREEZE:
      return "ISSUER_FREEZE";
    case OperationType.ISSUER_UNFREEZE:
      return "ISSUER_UNFREEZE";
    case OperationType.ISSUER_BURN:
      return "ISSUER_BURN";
    case OperationType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum OnChainTransactionStatus {
  PENDING = 0,
  CONFIRMED = 1,
  WAITING_MINED = 2,
  MINED = 3,
  ATTACHING = 4,
  ATTACHED = 5,
  UNRECOGNIZED = -1,
}

export function onChainTransactionStatusFromJSON(object: any): OnChainTransactionStatus {
  switch (object) {
    case 0:
    case "PENDING":
      return OnChainTransactionStatus.PENDING;
    case 1:
    case "CONFIRMED":
      return OnChainTransactionStatus.CONFIRMED;
    case 2:
    case "WAITING_MINED":
      return OnChainTransactionStatus.WAITING_MINED;
    case 3:
    case "MINED":
      return OnChainTransactionStatus.MINED;
    case 4:
    case "ATTACHING":
      return OnChainTransactionStatus.ATTACHING;
    case 5:
    case "ATTACHED":
      return OnChainTransactionStatus.ATTACHED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return OnChainTransactionStatus.UNRECOGNIZED;
  }
}

export function onChainTransactionStatusToJSON(object: OnChainTransactionStatus): string {
  switch (object) {
    case OnChainTransactionStatus.PENDING:
      return "PENDING";
    case OnChainTransactionStatus.CONFIRMED:
      return "CONFIRMED";
    case OnChainTransactionStatus.WAITING_MINED:
      return "WAITING_MINED";
    case OnChainTransactionStatus.MINED:
      return "MINED";
    case OnChainTransactionStatus.ATTACHING:
      return "ATTACHING";
    case OnChainTransactionStatus.ATTACHED:
      return "ATTACHED";
    case OnChainTransactionStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum SparkTransactionStatus {
  STARTED = 0,
  SIGNED = 1,
  FINALIZED = 2,
  UNRECOGNIZED = -1,
}

export function sparkTransactionStatusFromJSON(object: any): SparkTransactionStatus {
  switch (object) {
    case 0:
    case "STARTED":
      return SparkTransactionStatus.STARTED;
    case 1:
    case "SIGNED":
      return SparkTransactionStatus.SIGNED;
    case 2:
    case "FINALIZED":
      return SparkTransactionStatus.FINALIZED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SparkTransactionStatus.UNRECOGNIZED;
  }
}

export function sparkTransactionStatusToJSON(object: SparkTransactionStatus): string {
  switch (object) {
    case SparkTransactionStatus.STARTED:
      return "STARTED";
    case SparkTransactionStatus.SIGNED:
      return "SIGNED";
    case SparkTransactionStatus.FINALIZED:
      return "FINALIZED";
    case SparkTransactionStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface SparkSignatureData {
  sparkOperatorSignature: Uint8Array;
  sparkOperatorIdentityPublicKey: Uint8Array;
  leavesToSpendData: SparkSignatureLeafData[];
  finalTokenTransaction: TokenTransaction | undefined;
}

export interface SparkSignatureLeafData {
  spentLeafIndex: number;
  revocationPrivateKey?: Uint8Array | undefined;
}

/**
 * This proto is constructed by the wallet to specify leaves it wants to create
 * as part of a token transaction.
 */
export interface TokenLeafOutput {
  id: string;
  ownerPublicKey: Uint8Array;
  revocationPublicKey: Uint8Array;
  withdrawalBondSats: number;
  withdrawalLocktime: number;
  /** Public key representing the token. */
  tokenPublicKey: Uint8Array;
  /** Amount of tokens contained within this leaf (uint128). */
  tokenAmount: Uint8Array;
  isFrozen?: boolean | undefined;
}

/**
 * This proto is constructed by the wallet and is the core transaction data structure.
 * This proto is deterministically hashed to generate the token_transaction_hash that
 * is cooperatively signed by the SO group to confirm a token transaction.
 */
export interface TokenTransaction {
  /**
   * For mint transactions issuer_public_key will be specified without any leaves_to_spend.
   * For transfer transactions the token amount in the input leaves must match the token amount in the output leaves.
   */
  tokenInput?:
    | { $case: "mintInput"; mintInput: MintInput }
    | { $case: "transferInput"; transferInput: TransferInput }
    | undefined;
  outputLeaves: TokenLeafOutput[];
  sparkOperatorIdentityPublicKeys: Uint8Array[];
}

export interface TransferInput {
  leavesToSpend: TokenLeafToSpend[];
}

export interface MintInput {
  issuerPublicKey: Uint8Array;
  issuerProvidedTimestamp: number;
}

/**
 * This proto is constructed by the wallet (without a revocation private key initially)
 * to specify leaves it wants to spend as part of a token transaction. Upon sending
 * the private key field will be filled and returned by the Coordinator SO so that the
 * wallet can validate the full transaction hash before finalizng the transaction.
 */
export interface TokenLeafToSpend {
  prevTokenTransactionHash: Uint8Array;
  prevTokenTransactionLeafVout: number;
}

export interface FreezeTokensPayload {
  ownerPublicKey: Uint8Array;
  tokenPublicKey: Uint8Array;
  timestamp: number;
  operatorIdentityPublicKey: Uint8Array;
  /** Set to false when requesting a freeze. */
  shouldUnfreeze: boolean;
}

export interface TokenTransactionResponse {
  finalized: boolean;
  finalTokenTransaction: TokenTransaction | undefined;
  finalTokenTransactionHash: Uint8Array;
}

export interface Transaction {
  transaction?:
    | { $case: "onChain"; onChain: OnChainTransaction }
    | { $case: "spark"; spark: SparkTransaction }
    | undefined;
}

export interface ListAllTokenTransactionsCursor {
  /** tx_hash of the last tx fetched */
  lastTransactionHash: Uint8Array;
  /** whether the last_tx_hash is on chain */
  layer: Layer;
}

export interface OnChainTokenOutput {
  rawTx: Uint8Array;
  vout: number;
  amountSats: number;
  tokenPublicKey?: string | undefined;
  tokenAmount?: Uint8Array | undefined;
}

export interface OnChainTransaction {
  operationType: OperationType;
  transactionHash: Uint8Array;
  rawtx: Uint8Array;
  status: OnChainTransactionStatus;
  inputs: OnChainTokenOutput[];
  outputs: OnChainTokenOutput[];
  broadcastedAt: Date | undefined;
  confirmedAt: Date | undefined;
}

export interface SparkTransaction {
  operationType: OperationType;
  transactionHash: Uint8Array;
  status: SparkTransactionStatus;
  confirmedAt: Date | undefined;
  leavesToCreate: SparkLeaf[];
  leavesToSpend: SparkLeaf[];
  sparkOperatorIdentityPublicKeys: Uint8Array[];
}

export interface SparkLeaf {
  tokenPublicKey: Uint8Array;
  id: string;
  ownerPublicKey: Uint8Array;
  revocationPublicKey: Uint8Array;
  withdrawalBondSats: number;
  withdrawalLocktime: number;
  tokenAmount: Uint8Array;
  createTxHash: Uint8Array;
  createTxVoutIndex: number;
  spendTxHash?: Uint8Array | undefined;
  spendTxVoutIndex?: number | undefined;
  isFrozen?: boolean | undefined;
}

export interface Token {
  name: string;
  symbol: string;
  publicKey: string;
  decimals?: number | undefined;
  isFreezable?: boolean | undefined;
  maxSupply?: Uint8Array | undefined;
  totalSupply: Uint8Array;
  l1Supply: Uint8Array;
  sparkSupply: Uint8Array;
  totalOwnedByIssuer: Uint8Array;
  totalFrozen: Uint8Array;
}

export interface BlockInfo {
  blockHash: Uint8Array;
  blockHeight: number;
  minedAt: Date | undefined;
}

export interface TokenPubkey {
  publicKey: Uint8Array;
}

export interface TokenPubkeyAnnouncement {
  publicKey: TokenPubkey | undefined;
  name: string;
  symbol: string;
  decimal: Uint8Array;
  /** u128 */
  maxSupply: Uint8Array;
  isFreezable: boolean;
}

function createBaseSparkSignatureData(): SparkSignatureData {
  return {
    sparkOperatorSignature: new Uint8Array(0),
    sparkOperatorIdentityPublicKey: new Uint8Array(0),
    leavesToSpendData: [],
    finalTokenTransaction: undefined,
  };
}

export const SparkSignatureData: MessageFns<SparkSignatureData> = {
  encode(message: SparkSignatureData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sparkOperatorSignature.length !== 0) {
      writer.uint32(10).bytes(message.sparkOperatorSignature);
    }
    if (message.sparkOperatorIdentityPublicKey.length !== 0) {
      writer.uint32(18).bytes(message.sparkOperatorIdentityPublicKey);
    }
    for (const v of message.leavesToSpendData) {
      SparkSignatureLeafData.encode(v!, writer.uint32(26).fork()).join();
    }
    if (message.finalTokenTransaction !== undefined) {
      TokenTransaction.encode(message.finalTokenTransaction, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SparkSignatureData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSparkSignatureData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sparkOperatorSignature = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.sparkOperatorIdentityPublicKey = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.leavesToSpendData.push(SparkSignatureLeafData.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.finalTokenTransaction = TokenTransaction.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SparkSignatureData {
    return {
      sparkOperatorSignature: isSet(object.sparkOperatorSignature)
        ? bytesFromBase64(object.sparkOperatorSignature)
        : new Uint8Array(0),
      sparkOperatorIdentityPublicKey: isSet(object.sparkOperatorIdentityPublicKey)
        ? bytesFromBase64(object.sparkOperatorIdentityPublicKey)
        : new Uint8Array(0),
      leavesToSpendData: globalThis.Array.isArray(object?.leavesToSpendData)
        ? object.leavesToSpendData.map((e: any) => SparkSignatureLeafData.fromJSON(e))
        : [],
      finalTokenTransaction: isSet(object.finalTokenTransaction)
        ? TokenTransaction.fromJSON(object.finalTokenTransaction)
        : undefined,
    };
  },

  toJSON(message: SparkSignatureData): unknown {
    const obj: any = {};
    if (message.sparkOperatorSignature.length !== 0) {
      obj.sparkOperatorSignature = base64FromBytes(message.sparkOperatorSignature);
    }
    if (message.sparkOperatorIdentityPublicKey.length !== 0) {
      obj.sparkOperatorIdentityPublicKey = base64FromBytes(message.sparkOperatorIdentityPublicKey);
    }
    if (message.leavesToSpendData?.length) {
      obj.leavesToSpendData = message.leavesToSpendData.map((e) => SparkSignatureLeafData.toJSON(e));
    }
    if (message.finalTokenTransaction !== undefined) {
      obj.finalTokenTransaction = TokenTransaction.toJSON(message.finalTokenTransaction);
    }
    return obj;
  },

  create(base?: DeepPartial<SparkSignatureData>): SparkSignatureData {
    return SparkSignatureData.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SparkSignatureData>): SparkSignatureData {
    const message = createBaseSparkSignatureData();
    message.sparkOperatorSignature = object.sparkOperatorSignature ?? new Uint8Array(0);
    message.sparkOperatorIdentityPublicKey = object.sparkOperatorIdentityPublicKey ?? new Uint8Array(0);
    message.leavesToSpendData = object.leavesToSpendData?.map((e) => SparkSignatureLeafData.fromPartial(e)) || [];
    message.finalTokenTransaction =
      (object.finalTokenTransaction !== undefined && object.finalTokenTransaction !== null)
        ? TokenTransaction.fromPartial(object.finalTokenTransaction)
        : undefined;
    return message;
  },
};

function createBaseSparkSignatureLeafData(): SparkSignatureLeafData {
  return { spentLeafIndex: 0, revocationPrivateKey: undefined };
}

export const SparkSignatureLeafData: MessageFns<SparkSignatureLeafData> = {
  encode(message: SparkSignatureLeafData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.spentLeafIndex !== 0) {
      writer.uint32(8).uint32(message.spentLeafIndex);
    }
    if (message.revocationPrivateKey !== undefined) {
      writer.uint32(18).bytes(message.revocationPrivateKey);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SparkSignatureLeafData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSparkSignatureLeafData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.spentLeafIndex = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.revocationPrivateKey = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SparkSignatureLeafData {
    return {
      spentLeafIndex: isSet(object.spentLeafIndex) ? globalThis.Number(object.spentLeafIndex) : 0,
      revocationPrivateKey: isSet(object.revocationPrivateKey)
        ? bytesFromBase64(object.revocationPrivateKey)
        : undefined,
    };
  },

  toJSON(message: SparkSignatureLeafData): unknown {
    const obj: any = {};
    if (message.spentLeafIndex !== 0) {
      obj.spentLeafIndex = Math.round(message.spentLeafIndex);
    }
    if (message.revocationPrivateKey !== undefined) {
      obj.revocationPrivateKey = base64FromBytes(message.revocationPrivateKey);
    }
    return obj;
  },

  create(base?: DeepPartial<SparkSignatureLeafData>): SparkSignatureLeafData {
    return SparkSignatureLeafData.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SparkSignatureLeafData>): SparkSignatureLeafData {
    const message = createBaseSparkSignatureLeafData();
    message.spentLeafIndex = object.spentLeafIndex ?? 0;
    message.revocationPrivateKey = object.revocationPrivateKey ?? undefined;
    return message;
  },
};

function createBaseTokenLeafOutput(): TokenLeafOutput {
  return {
    id: "",
    ownerPublicKey: new Uint8Array(0),
    revocationPublicKey: new Uint8Array(0),
    withdrawalBondSats: 0,
    withdrawalLocktime: 0,
    tokenPublicKey: new Uint8Array(0),
    tokenAmount: new Uint8Array(0),
    isFrozen: undefined,
  };
}

export const TokenLeafOutput: MessageFns<TokenLeafOutput> = {
  encode(message: TokenLeafOutput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.ownerPublicKey.length !== 0) {
      writer.uint32(18).bytes(message.ownerPublicKey);
    }
    if (message.revocationPublicKey.length !== 0) {
      writer.uint32(26).bytes(message.revocationPublicKey);
    }
    if (message.withdrawalBondSats !== 0) {
      writer.uint32(32).uint64(message.withdrawalBondSats);
    }
    if (message.withdrawalLocktime !== 0) {
      writer.uint32(40).uint64(message.withdrawalLocktime);
    }
    if (message.tokenPublicKey.length !== 0) {
      writer.uint32(50).bytes(message.tokenPublicKey);
    }
    if (message.tokenAmount.length !== 0) {
      writer.uint32(58).bytes(message.tokenAmount);
    }
    if (message.isFrozen !== undefined) {
      writer.uint32(64).bool(message.isFrozen);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TokenLeafOutput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTokenLeafOutput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.ownerPublicKey = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.revocationPublicKey = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.withdrawalBondSats = longToNumber(reader.uint64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.withdrawalLocktime = longToNumber(reader.uint64());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.tokenPublicKey = reader.bytes();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.tokenAmount = reader.bytes();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.isFrozen = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TokenLeafOutput {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      ownerPublicKey: isSet(object.ownerPublicKey) ? bytesFromBase64(object.ownerPublicKey) : new Uint8Array(0),
      revocationPublicKey: isSet(object.revocationPublicKey)
        ? bytesFromBase64(object.revocationPublicKey)
        : new Uint8Array(0),
      withdrawalBondSats: isSet(object.withdrawalBondSats) ? globalThis.Number(object.withdrawalBondSats) : 0,
      withdrawalLocktime: isSet(object.withdrawalLocktime) ? globalThis.Number(object.withdrawalLocktime) : 0,
      tokenPublicKey: isSet(object.tokenPublicKey) ? bytesFromBase64(object.tokenPublicKey) : new Uint8Array(0),
      tokenAmount: isSet(object.tokenAmount) ? bytesFromBase64(object.tokenAmount) : new Uint8Array(0),
      isFrozen: isSet(object.isFrozen) ? globalThis.Boolean(object.isFrozen) : undefined,
    };
  },

  toJSON(message: TokenLeafOutput): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.ownerPublicKey.length !== 0) {
      obj.ownerPublicKey = base64FromBytes(message.ownerPublicKey);
    }
    if (message.revocationPublicKey.length !== 0) {
      obj.revocationPublicKey = base64FromBytes(message.revocationPublicKey);
    }
    if (message.withdrawalBondSats !== 0) {
      obj.withdrawalBondSats = Math.round(message.withdrawalBondSats);
    }
    if (message.withdrawalLocktime !== 0) {
      obj.withdrawalLocktime = Math.round(message.withdrawalLocktime);
    }
    if (message.tokenPublicKey.length !== 0) {
      obj.tokenPublicKey = base64FromBytes(message.tokenPublicKey);
    }
    if (message.tokenAmount.length !== 0) {
      obj.tokenAmount = base64FromBytes(message.tokenAmount);
    }
    if (message.isFrozen !== undefined) {
      obj.isFrozen = message.isFrozen;
    }
    return obj;
  },

  create(base?: DeepPartial<TokenLeafOutput>): TokenLeafOutput {
    return TokenLeafOutput.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<TokenLeafOutput>): TokenLeafOutput {
    const message = createBaseTokenLeafOutput();
    message.id = object.id ?? "";
    message.ownerPublicKey = object.ownerPublicKey ?? new Uint8Array(0);
    message.revocationPublicKey = object.revocationPublicKey ?? new Uint8Array(0);
    message.withdrawalBondSats = object.withdrawalBondSats ?? 0;
    message.withdrawalLocktime = object.withdrawalLocktime ?? 0;
    message.tokenPublicKey = object.tokenPublicKey ?? new Uint8Array(0);
    message.tokenAmount = object.tokenAmount ?? new Uint8Array(0);
    message.isFrozen = object.isFrozen ?? undefined;
    return message;
  },
};

function createBaseTokenTransaction(): TokenTransaction {
  return { tokenInput: undefined, outputLeaves: [], sparkOperatorIdentityPublicKeys: [] };
}

export const TokenTransaction: MessageFns<TokenTransaction> = {
  encode(message: TokenTransaction, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    switch (message.tokenInput?.$case) {
      case "mintInput":
        MintInput.encode(message.tokenInput.mintInput, writer.uint32(10).fork()).join();
        break;
      case "transferInput":
        TransferInput.encode(message.tokenInput.transferInput, writer.uint32(18).fork()).join();
        break;
    }
    for (const v of message.outputLeaves) {
      TokenLeafOutput.encode(v!, writer.uint32(26).fork()).join();
    }
    for (const v of message.sparkOperatorIdentityPublicKeys) {
      writer.uint32(34).bytes(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TokenTransaction {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTokenTransaction();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tokenInput = { $case: "mintInput", mintInput: MintInput.decode(reader, reader.uint32()) };
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tokenInput = { $case: "transferInput", transferInput: TransferInput.decode(reader, reader.uint32()) };
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.outputLeaves.push(TokenLeafOutput.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.sparkOperatorIdentityPublicKeys.push(reader.bytes());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TokenTransaction {
    return {
      tokenInput: isSet(object.mintInput)
        ? { $case: "mintInput", mintInput: MintInput.fromJSON(object.mintInput) }
        : isSet(object.transferInput)
        ? { $case: "transferInput", transferInput: TransferInput.fromJSON(object.transferInput) }
        : undefined,
      outputLeaves: globalThis.Array.isArray(object?.outputLeaves)
        ? object.outputLeaves.map((e: any) => TokenLeafOutput.fromJSON(e))
        : [],
      sparkOperatorIdentityPublicKeys: globalThis.Array.isArray(object?.sparkOperatorIdentityPublicKeys)
        ? object.sparkOperatorIdentityPublicKeys.map((e: any) => bytesFromBase64(e))
        : [],
    };
  },

  toJSON(message: TokenTransaction): unknown {
    const obj: any = {};
    if (message.tokenInput?.$case === "mintInput") {
      obj.mintInput = MintInput.toJSON(message.tokenInput.mintInput);
    } else if (message.tokenInput?.$case === "transferInput") {
      obj.transferInput = TransferInput.toJSON(message.tokenInput.transferInput);
    }
    if (message.outputLeaves?.length) {
      obj.outputLeaves = message.outputLeaves.map((e) => TokenLeafOutput.toJSON(e));
    }
    if (message.sparkOperatorIdentityPublicKeys?.length) {
      obj.sparkOperatorIdentityPublicKeys = message.sparkOperatorIdentityPublicKeys.map((e) => base64FromBytes(e));
    }
    return obj;
  },

  create(base?: DeepPartial<TokenTransaction>): TokenTransaction {
    return TokenTransaction.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<TokenTransaction>): TokenTransaction {
    const message = createBaseTokenTransaction();
    switch (object.tokenInput?.$case) {
      case "mintInput": {
        if (object.tokenInput?.mintInput !== undefined && object.tokenInput?.mintInput !== null) {
          message.tokenInput = { $case: "mintInput", mintInput: MintInput.fromPartial(object.tokenInput.mintInput) };
        }
        break;
      }
      case "transferInput": {
        if (object.tokenInput?.transferInput !== undefined && object.tokenInput?.transferInput !== null) {
          message.tokenInput = {
            $case: "transferInput",
            transferInput: TransferInput.fromPartial(object.tokenInput.transferInput),
          };
        }
        break;
      }
    }
    message.outputLeaves = object.outputLeaves?.map((e) => TokenLeafOutput.fromPartial(e)) || [];
    message.sparkOperatorIdentityPublicKeys = object.sparkOperatorIdentityPublicKeys?.map((e) => e) || [];
    return message;
  },
};

function createBaseTransferInput(): TransferInput {
  return { leavesToSpend: [] };
}

export const TransferInput: MessageFns<TransferInput> = {
  encode(message: TransferInput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.leavesToSpend) {
      TokenLeafToSpend.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TransferInput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTransferInput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.leavesToSpend.push(TokenLeafToSpend.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TransferInput {
    return {
      leavesToSpend: globalThis.Array.isArray(object?.leavesToSpend)
        ? object.leavesToSpend.map((e: any) => TokenLeafToSpend.fromJSON(e))
        : [],
    };
  },

  toJSON(message: TransferInput): unknown {
    const obj: any = {};
    if (message.leavesToSpend?.length) {
      obj.leavesToSpend = message.leavesToSpend.map((e) => TokenLeafToSpend.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<TransferInput>): TransferInput {
    return TransferInput.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<TransferInput>): TransferInput {
    const message = createBaseTransferInput();
    message.leavesToSpend = object.leavesToSpend?.map((e) => TokenLeafToSpend.fromPartial(e)) || [];
    return message;
  },
};

function createBaseMintInput(): MintInput {
  return { issuerPublicKey: new Uint8Array(0), issuerProvidedTimestamp: 0 };
}

export const MintInput: MessageFns<MintInput> = {
  encode(message: MintInput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.issuerPublicKey.length !== 0) {
      writer.uint32(10).bytes(message.issuerPublicKey);
    }
    if (message.issuerProvidedTimestamp !== 0) {
      writer.uint32(16).uint64(message.issuerProvidedTimestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MintInput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMintInput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.issuerPublicKey = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.issuerProvidedTimestamp = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MintInput {
    return {
      issuerPublicKey: isSet(object.issuerPublicKey) ? bytesFromBase64(object.issuerPublicKey) : new Uint8Array(0),
      issuerProvidedTimestamp: isSet(object.issuerProvidedTimestamp)
        ? globalThis.Number(object.issuerProvidedTimestamp)
        : 0,
    };
  },

  toJSON(message: MintInput): unknown {
    const obj: any = {};
    if (message.issuerPublicKey.length !== 0) {
      obj.issuerPublicKey = base64FromBytes(message.issuerPublicKey);
    }
    if (message.issuerProvidedTimestamp !== 0) {
      obj.issuerProvidedTimestamp = Math.round(message.issuerProvidedTimestamp);
    }
    return obj;
  },

  create(base?: DeepPartial<MintInput>): MintInput {
    return MintInput.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MintInput>): MintInput {
    const message = createBaseMintInput();
    message.issuerPublicKey = object.issuerPublicKey ?? new Uint8Array(0);
    message.issuerProvidedTimestamp = object.issuerProvidedTimestamp ?? 0;
    return message;
  },
};

function createBaseTokenLeafToSpend(): TokenLeafToSpend {
  return { prevTokenTransactionHash: new Uint8Array(0), prevTokenTransactionLeafVout: 0 };
}

export const TokenLeafToSpend: MessageFns<TokenLeafToSpend> = {
  encode(message: TokenLeafToSpend, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.prevTokenTransactionHash.length !== 0) {
      writer.uint32(10).bytes(message.prevTokenTransactionHash);
    }
    if (message.prevTokenTransactionLeafVout !== 0) {
      writer.uint32(16).uint32(message.prevTokenTransactionLeafVout);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TokenLeafToSpend {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTokenLeafToSpend();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.prevTokenTransactionHash = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.prevTokenTransactionLeafVout = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TokenLeafToSpend {
    return {
      prevTokenTransactionHash: isSet(object.prevTokenTransactionHash)
        ? bytesFromBase64(object.prevTokenTransactionHash)
        : new Uint8Array(0),
      prevTokenTransactionLeafVout: isSet(object.prevTokenTransactionLeafVout)
        ? globalThis.Number(object.prevTokenTransactionLeafVout)
        : 0,
    };
  },

  toJSON(message: TokenLeafToSpend): unknown {
    const obj: any = {};
    if (message.prevTokenTransactionHash.length !== 0) {
      obj.prevTokenTransactionHash = base64FromBytes(message.prevTokenTransactionHash);
    }
    if (message.prevTokenTransactionLeafVout !== 0) {
      obj.prevTokenTransactionLeafVout = Math.round(message.prevTokenTransactionLeafVout);
    }
    return obj;
  },

  create(base?: DeepPartial<TokenLeafToSpend>): TokenLeafToSpend {
    return TokenLeafToSpend.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<TokenLeafToSpend>): TokenLeafToSpend {
    const message = createBaseTokenLeafToSpend();
    message.prevTokenTransactionHash = object.prevTokenTransactionHash ?? new Uint8Array(0);
    message.prevTokenTransactionLeafVout = object.prevTokenTransactionLeafVout ?? 0;
    return message;
  },
};

function createBaseFreezeTokensPayload(): FreezeTokensPayload {
  return {
    ownerPublicKey: new Uint8Array(0),
    tokenPublicKey: new Uint8Array(0),
    timestamp: 0,
    operatorIdentityPublicKey: new Uint8Array(0),
    shouldUnfreeze: false,
  };
}

export const FreezeTokensPayload: MessageFns<FreezeTokensPayload> = {
  encode(message: FreezeTokensPayload, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ownerPublicKey.length !== 0) {
      writer.uint32(10).bytes(message.ownerPublicKey);
    }
    if (message.tokenPublicKey.length !== 0) {
      writer.uint32(18).bytes(message.tokenPublicKey);
    }
    if (message.timestamp !== 0) {
      writer.uint32(24).uint64(message.timestamp);
    }
    if (message.operatorIdentityPublicKey.length !== 0) {
      writer.uint32(34).bytes(message.operatorIdentityPublicKey);
    }
    if (message.shouldUnfreeze !== false) {
      writer.uint32(40).bool(message.shouldUnfreeze);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FreezeTokensPayload {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFreezeTokensPayload();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ownerPublicKey = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tokenPublicKey = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.timestamp = longToNumber(reader.uint64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.operatorIdentityPublicKey = reader.bytes();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.shouldUnfreeze = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FreezeTokensPayload {
    return {
      ownerPublicKey: isSet(object.ownerPublicKey) ? bytesFromBase64(object.ownerPublicKey) : new Uint8Array(0),
      tokenPublicKey: isSet(object.tokenPublicKey) ? bytesFromBase64(object.tokenPublicKey) : new Uint8Array(0),
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
      operatorIdentityPublicKey: isSet(object.operatorIdentityPublicKey)
        ? bytesFromBase64(object.operatorIdentityPublicKey)
        : new Uint8Array(0),
      shouldUnfreeze: isSet(object.shouldUnfreeze) ? globalThis.Boolean(object.shouldUnfreeze) : false,
    };
  },

  toJSON(message: FreezeTokensPayload): unknown {
    const obj: any = {};
    if (message.ownerPublicKey.length !== 0) {
      obj.ownerPublicKey = base64FromBytes(message.ownerPublicKey);
    }
    if (message.tokenPublicKey.length !== 0) {
      obj.tokenPublicKey = base64FromBytes(message.tokenPublicKey);
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    if (message.operatorIdentityPublicKey.length !== 0) {
      obj.operatorIdentityPublicKey = base64FromBytes(message.operatorIdentityPublicKey);
    }
    if (message.shouldUnfreeze !== false) {
      obj.shouldUnfreeze = message.shouldUnfreeze;
    }
    return obj;
  },

  create(base?: DeepPartial<FreezeTokensPayload>): FreezeTokensPayload {
    return FreezeTokensPayload.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<FreezeTokensPayload>): FreezeTokensPayload {
    const message = createBaseFreezeTokensPayload();
    message.ownerPublicKey = object.ownerPublicKey ?? new Uint8Array(0);
    message.tokenPublicKey = object.tokenPublicKey ?? new Uint8Array(0);
    message.timestamp = object.timestamp ?? 0;
    message.operatorIdentityPublicKey = object.operatorIdentityPublicKey ?? new Uint8Array(0);
    message.shouldUnfreeze = object.shouldUnfreeze ?? false;
    return message;
  },
};

function createBaseTokenTransactionResponse(): TokenTransactionResponse {
  return { finalized: false, finalTokenTransaction: undefined, finalTokenTransactionHash: new Uint8Array(0) };
}

export const TokenTransactionResponse: MessageFns<TokenTransactionResponse> = {
  encode(message: TokenTransactionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.finalized !== false) {
      writer.uint32(8).bool(message.finalized);
    }
    if (message.finalTokenTransaction !== undefined) {
      TokenTransaction.encode(message.finalTokenTransaction, writer.uint32(18).fork()).join();
    }
    if (message.finalTokenTransactionHash.length !== 0) {
      writer.uint32(26).bytes(message.finalTokenTransactionHash);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TokenTransactionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTokenTransactionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.finalized = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.finalTokenTransaction = TokenTransaction.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.finalTokenTransactionHash = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TokenTransactionResponse {
    return {
      finalized: isSet(object.finalized) ? globalThis.Boolean(object.finalized) : false,
      finalTokenTransaction: isSet(object.finalTokenTransaction)
        ? TokenTransaction.fromJSON(object.finalTokenTransaction)
        : undefined,
      finalTokenTransactionHash: isSet(object.finalTokenTransactionHash)
        ? bytesFromBase64(object.finalTokenTransactionHash)
        : new Uint8Array(0),
    };
  },

  toJSON(message: TokenTransactionResponse): unknown {
    const obj: any = {};
    if (message.finalized !== false) {
      obj.finalized = message.finalized;
    }
    if (message.finalTokenTransaction !== undefined) {
      obj.finalTokenTransaction = TokenTransaction.toJSON(message.finalTokenTransaction);
    }
    if (message.finalTokenTransactionHash.length !== 0) {
      obj.finalTokenTransactionHash = base64FromBytes(message.finalTokenTransactionHash);
    }
    return obj;
  },

  create(base?: DeepPartial<TokenTransactionResponse>): TokenTransactionResponse {
    return TokenTransactionResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<TokenTransactionResponse>): TokenTransactionResponse {
    const message = createBaseTokenTransactionResponse();
    message.finalized = object.finalized ?? false;
    message.finalTokenTransaction =
      (object.finalTokenTransaction !== undefined && object.finalTokenTransaction !== null)
        ? TokenTransaction.fromPartial(object.finalTokenTransaction)
        : undefined;
    message.finalTokenTransactionHash = object.finalTokenTransactionHash ?? new Uint8Array(0);
    return message;
  },
};

function createBaseTransaction(): Transaction {
  return { transaction: undefined };
}

export const Transaction: MessageFns<Transaction> = {
  encode(message: Transaction, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    switch (message.transaction?.$case) {
      case "onChain":
        OnChainTransaction.encode(message.transaction.onChain, writer.uint32(10).fork()).join();
        break;
      case "spark":
        SparkTransaction.encode(message.transaction.spark, writer.uint32(18).fork()).join();
        break;
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Transaction {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTransaction();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.transaction = { $case: "onChain", onChain: OnChainTransaction.decode(reader, reader.uint32()) };
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.transaction = { $case: "spark", spark: SparkTransaction.decode(reader, reader.uint32()) };
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Transaction {
    return {
      transaction: isSet(object.onChain)
        ? { $case: "onChain", onChain: OnChainTransaction.fromJSON(object.onChain) }
        : isSet(object.spark)
        ? { $case: "spark", spark: SparkTransaction.fromJSON(object.spark) }
        : undefined,
    };
  },

  toJSON(message: Transaction): unknown {
    const obj: any = {};
    if (message.transaction?.$case === "onChain") {
      obj.onChain = OnChainTransaction.toJSON(message.transaction.onChain);
    } else if (message.transaction?.$case === "spark") {
      obj.spark = SparkTransaction.toJSON(message.transaction.spark);
    }
    return obj;
  },

  create(base?: DeepPartial<Transaction>): Transaction {
    return Transaction.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Transaction>): Transaction {
    const message = createBaseTransaction();
    switch (object.transaction?.$case) {
      case "onChain": {
        if (object.transaction?.onChain !== undefined && object.transaction?.onChain !== null) {
          message.transaction = {
            $case: "onChain",
            onChain: OnChainTransaction.fromPartial(object.transaction.onChain),
          };
        }
        break;
      }
      case "spark": {
        if (object.transaction?.spark !== undefined && object.transaction?.spark !== null) {
          message.transaction = { $case: "spark", spark: SparkTransaction.fromPartial(object.transaction.spark) };
        }
        break;
      }
    }
    return message;
  },
};

function createBaseListAllTokenTransactionsCursor(): ListAllTokenTransactionsCursor {
  return { lastTransactionHash: new Uint8Array(0), layer: 0 };
}

export const ListAllTokenTransactionsCursor: MessageFns<ListAllTokenTransactionsCursor> = {
  encode(message: ListAllTokenTransactionsCursor, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.lastTransactionHash.length !== 0) {
      writer.uint32(10).bytes(message.lastTransactionHash);
    }
    if (message.layer !== 0) {
      writer.uint32(16).int32(message.layer);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListAllTokenTransactionsCursor {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListAllTokenTransactionsCursor();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.lastTransactionHash = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.layer = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListAllTokenTransactionsCursor {
    return {
      lastTransactionHash: isSet(object.lastTransactionHash)
        ? bytesFromBase64(object.lastTransactionHash)
        : new Uint8Array(0),
      layer: isSet(object.layer) ? layerFromJSON(object.layer) : 0,
    };
  },

  toJSON(message: ListAllTokenTransactionsCursor): unknown {
    const obj: any = {};
    if (message.lastTransactionHash.length !== 0) {
      obj.lastTransactionHash = base64FromBytes(message.lastTransactionHash);
    }
    if (message.layer !== 0) {
      obj.layer = layerToJSON(message.layer);
    }
    return obj;
  },

  create(base?: DeepPartial<ListAllTokenTransactionsCursor>): ListAllTokenTransactionsCursor {
    return ListAllTokenTransactionsCursor.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListAllTokenTransactionsCursor>): ListAllTokenTransactionsCursor {
    const message = createBaseListAllTokenTransactionsCursor();
    message.lastTransactionHash = object.lastTransactionHash ?? new Uint8Array(0);
    message.layer = object.layer ?? 0;
    return message;
  },
};

function createBaseOnChainTokenOutput(): OnChainTokenOutput {
  return { rawTx: new Uint8Array(0), vout: 0, amountSats: 0, tokenPublicKey: undefined, tokenAmount: undefined };
}

export const OnChainTokenOutput: MessageFns<OnChainTokenOutput> = {
  encode(message: OnChainTokenOutput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.rawTx.length !== 0) {
      writer.uint32(10).bytes(message.rawTx);
    }
    if (message.vout !== 0) {
      writer.uint32(16).uint32(message.vout);
    }
    if (message.amountSats !== 0) {
      writer.uint32(24).uint64(message.amountSats);
    }
    if (message.tokenPublicKey !== undefined) {
      writer.uint32(34).string(message.tokenPublicKey);
    }
    if (message.tokenAmount !== undefined) {
      writer.uint32(42).bytes(message.tokenAmount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OnChainTokenOutput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOnChainTokenOutput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.rawTx = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.vout = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.amountSats = longToNumber(reader.uint64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.tokenPublicKey = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.tokenAmount = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OnChainTokenOutput {
    return {
      rawTx: isSet(object.rawTx) ? bytesFromBase64(object.rawTx) : new Uint8Array(0),
      vout: isSet(object.vout) ? globalThis.Number(object.vout) : 0,
      amountSats: isSet(object.amountSats) ? globalThis.Number(object.amountSats) : 0,
      tokenPublicKey: isSet(object.tokenPublicKey) ? globalThis.String(object.tokenPublicKey) : undefined,
      tokenAmount: isSet(object.tokenAmount) ? bytesFromBase64(object.tokenAmount) : undefined,
    };
  },

  toJSON(message: OnChainTokenOutput): unknown {
    const obj: any = {};
    if (message.rawTx.length !== 0) {
      obj.rawTx = base64FromBytes(message.rawTx);
    }
    if (message.vout !== 0) {
      obj.vout = Math.round(message.vout);
    }
    if (message.amountSats !== 0) {
      obj.amountSats = Math.round(message.amountSats);
    }
    if (message.tokenPublicKey !== undefined) {
      obj.tokenPublicKey = message.tokenPublicKey;
    }
    if (message.tokenAmount !== undefined) {
      obj.tokenAmount = base64FromBytes(message.tokenAmount);
    }
    return obj;
  },

  create(base?: DeepPartial<OnChainTokenOutput>): OnChainTokenOutput {
    return OnChainTokenOutput.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<OnChainTokenOutput>): OnChainTokenOutput {
    const message = createBaseOnChainTokenOutput();
    message.rawTx = object.rawTx ?? new Uint8Array(0);
    message.vout = object.vout ?? 0;
    message.amountSats = object.amountSats ?? 0;
    message.tokenPublicKey = object.tokenPublicKey ?? undefined;
    message.tokenAmount = object.tokenAmount ?? undefined;
    return message;
  },
};

function createBaseOnChainTransaction(): OnChainTransaction {
  return {
    operationType: 0,
    transactionHash: new Uint8Array(0),
    rawtx: new Uint8Array(0),
    status: 0,
    inputs: [],
    outputs: [],
    broadcastedAt: undefined,
    confirmedAt: undefined,
  };
}

export const OnChainTransaction: MessageFns<OnChainTransaction> = {
  encode(message: OnChainTransaction, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.operationType !== 0) {
      writer.uint32(8).int32(message.operationType);
    }
    if (message.transactionHash.length !== 0) {
      writer.uint32(18).bytes(message.transactionHash);
    }
    if (message.rawtx.length !== 0) {
      writer.uint32(26).bytes(message.rawtx);
    }
    if (message.status !== 0) {
      writer.uint32(32).int32(message.status);
    }
    for (const v of message.inputs) {
      OnChainTokenOutput.encode(v!, writer.uint32(42).fork()).join();
    }
    for (const v of message.outputs) {
      OnChainTokenOutput.encode(v!, writer.uint32(50).fork()).join();
    }
    if (message.broadcastedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.broadcastedAt), writer.uint32(58).fork()).join();
    }
    if (message.confirmedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.confirmedAt), writer.uint32(66).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OnChainTransaction {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOnChainTransaction();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.operationType = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.transactionHash = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.rawtx = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.inputs.push(OnChainTokenOutput.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.outputs.push(OnChainTokenOutput.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.broadcastedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.confirmedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OnChainTransaction {
    return {
      operationType: isSet(object.operationType) ? operationTypeFromJSON(object.operationType) : 0,
      transactionHash: isSet(object.transactionHash) ? bytesFromBase64(object.transactionHash) : new Uint8Array(0),
      rawtx: isSet(object.rawtx) ? bytesFromBase64(object.rawtx) : new Uint8Array(0),
      status: isSet(object.status) ? onChainTransactionStatusFromJSON(object.status) : 0,
      inputs: globalThis.Array.isArray(object?.inputs)
        ? object.inputs.map((e: any) => OnChainTokenOutput.fromJSON(e))
        : [],
      outputs: globalThis.Array.isArray(object?.outputs)
        ? object.outputs.map((e: any) => OnChainTokenOutput.fromJSON(e))
        : [],
      broadcastedAt: isSet(object.broadcastedAt) ? fromJsonTimestamp(object.broadcastedAt) : undefined,
      confirmedAt: isSet(object.confirmedAt) ? fromJsonTimestamp(object.confirmedAt) : undefined,
    };
  },

  toJSON(message: OnChainTransaction): unknown {
    const obj: any = {};
    if (message.operationType !== 0) {
      obj.operationType = operationTypeToJSON(message.operationType);
    }
    if (message.transactionHash.length !== 0) {
      obj.transactionHash = base64FromBytes(message.transactionHash);
    }
    if (message.rawtx.length !== 0) {
      obj.rawtx = base64FromBytes(message.rawtx);
    }
    if (message.status !== 0) {
      obj.status = onChainTransactionStatusToJSON(message.status);
    }
    if (message.inputs?.length) {
      obj.inputs = message.inputs.map((e) => OnChainTokenOutput.toJSON(e));
    }
    if (message.outputs?.length) {
      obj.outputs = message.outputs.map((e) => OnChainTokenOutput.toJSON(e));
    }
    if (message.broadcastedAt !== undefined) {
      obj.broadcastedAt = message.broadcastedAt.toISOString();
    }
    if (message.confirmedAt !== undefined) {
      obj.confirmedAt = message.confirmedAt.toISOString();
    }
    return obj;
  },

  create(base?: DeepPartial<OnChainTransaction>): OnChainTransaction {
    return OnChainTransaction.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<OnChainTransaction>): OnChainTransaction {
    const message = createBaseOnChainTransaction();
    message.operationType = object.operationType ?? 0;
    message.transactionHash = object.transactionHash ?? new Uint8Array(0);
    message.rawtx = object.rawtx ?? new Uint8Array(0);
    message.status = object.status ?? 0;
    message.inputs = object.inputs?.map((e) => OnChainTokenOutput.fromPartial(e)) || [];
    message.outputs = object.outputs?.map((e) => OnChainTokenOutput.fromPartial(e)) || [];
    message.broadcastedAt = object.broadcastedAt ?? undefined;
    message.confirmedAt = object.confirmedAt ?? undefined;
    return message;
  },
};

function createBaseSparkTransaction(): SparkTransaction {
  return {
    operationType: 0,
    transactionHash: new Uint8Array(0),
    status: 0,
    confirmedAt: undefined,
    leavesToCreate: [],
    leavesToSpend: [],
    sparkOperatorIdentityPublicKeys: [],
  };
}

export const SparkTransaction: MessageFns<SparkTransaction> = {
  encode(message: SparkTransaction, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.operationType !== 0) {
      writer.uint32(8).int32(message.operationType);
    }
    if (message.transactionHash.length !== 0) {
      writer.uint32(18).bytes(message.transactionHash);
    }
    if (message.status !== 0) {
      writer.uint32(24).int32(message.status);
    }
    if (message.confirmedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.confirmedAt), writer.uint32(34).fork()).join();
    }
    for (const v of message.leavesToCreate) {
      SparkLeaf.encode(v!, writer.uint32(42).fork()).join();
    }
    for (const v of message.leavesToSpend) {
      SparkLeaf.encode(v!, writer.uint32(50).fork()).join();
    }
    for (const v of message.sparkOperatorIdentityPublicKeys) {
      writer.uint32(58).bytes(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SparkTransaction {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSparkTransaction();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.operationType = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.transactionHash = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.confirmedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.leavesToCreate.push(SparkLeaf.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.leavesToSpend.push(SparkLeaf.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.sparkOperatorIdentityPublicKeys.push(reader.bytes());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SparkTransaction {
    return {
      operationType: isSet(object.operationType) ? operationTypeFromJSON(object.operationType) : 0,
      transactionHash: isSet(object.transactionHash) ? bytesFromBase64(object.transactionHash) : new Uint8Array(0),
      status: isSet(object.status) ? sparkTransactionStatusFromJSON(object.status) : 0,
      confirmedAt: isSet(object.confirmedAt) ? fromJsonTimestamp(object.confirmedAt) : undefined,
      leavesToCreate: globalThis.Array.isArray(object?.leavesToCreate)
        ? object.leavesToCreate.map((e: any) => SparkLeaf.fromJSON(e))
        : [],
      leavesToSpend: globalThis.Array.isArray(object?.leavesToSpend)
        ? object.leavesToSpend.map((e: any) => SparkLeaf.fromJSON(e))
        : [],
      sparkOperatorIdentityPublicKeys: globalThis.Array.isArray(object?.sparkOperatorIdentityPublicKeys)
        ? object.sparkOperatorIdentityPublicKeys.map((e: any) => bytesFromBase64(e))
        : [],
    };
  },

  toJSON(message: SparkTransaction): unknown {
    const obj: any = {};
    if (message.operationType !== 0) {
      obj.operationType = operationTypeToJSON(message.operationType);
    }
    if (message.transactionHash.length !== 0) {
      obj.transactionHash = base64FromBytes(message.transactionHash);
    }
    if (message.status !== 0) {
      obj.status = sparkTransactionStatusToJSON(message.status);
    }
    if (message.confirmedAt !== undefined) {
      obj.confirmedAt = message.confirmedAt.toISOString();
    }
    if (message.leavesToCreate?.length) {
      obj.leavesToCreate = message.leavesToCreate.map((e) => SparkLeaf.toJSON(e));
    }
    if (message.leavesToSpend?.length) {
      obj.leavesToSpend = message.leavesToSpend.map((e) => SparkLeaf.toJSON(e));
    }
    if (message.sparkOperatorIdentityPublicKeys?.length) {
      obj.sparkOperatorIdentityPublicKeys = message.sparkOperatorIdentityPublicKeys.map((e) => base64FromBytes(e));
    }
    return obj;
  },

  create(base?: DeepPartial<SparkTransaction>): SparkTransaction {
    return SparkTransaction.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SparkTransaction>): SparkTransaction {
    const message = createBaseSparkTransaction();
    message.operationType = object.operationType ?? 0;
    message.transactionHash = object.transactionHash ?? new Uint8Array(0);
    message.status = object.status ?? 0;
    message.confirmedAt = object.confirmedAt ?? undefined;
    message.leavesToCreate = object.leavesToCreate?.map((e) => SparkLeaf.fromPartial(e)) || [];
    message.leavesToSpend = object.leavesToSpend?.map((e) => SparkLeaf.fromPartial(e)) || [];
    message.sparkOperatorIdentityPublicKeys = object.sparkOperatorIdentityPublicKeys?.map((e) => e) || [];
    return message;
  },
};

function createBaseSparkLeaf(): SparkLeaf {
  return {
    tokenPublicKey: new Uint8Array(0),
    id: "",
    ownerPublicKey: new Uint8Array(0),
    revocationPublicKey: new Uint8Array(0),
    withdrawalBondSats: 0,
    withdrawalLocktime: 0,
    tokenAmount: new Uint8Array(0),
    createTxHash: new Uint8Array(0),
    createTxVoutIndex: 0,
    spendTxHash: undefined,
    spendTxVoutIndex: undefined,
    isFrozen: undefined,
  };
}

export const SparkLeaf: MessageFns<SparkLeaf> = {
  encode(message: SparkLeaf, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tokenPublicKey.length !== 0) {
      writer.uint32(10).bytes(message.tokenPublicKey);
    }
    if (message.id !== "") {
      writer.uint32(18).string(message.id);
    }
    if (message.ownerPublicKey.length !== 0) {
      writer.uint32(26).bytes(message.ownerPublicKey);
    }
    if (message.revocationPublicKey.length !== 0) {
      writer.uint32(34).bytes(message.revocationPublicKey);
    }
    if (message.withdrawalBondSats !== 0) {
      writer.uint32(40).uint64(message.withdrawalBondSats);
    }
    if (message.withdrawalLocktime !== 0) {
      writer.uint32(48).uint64(message.withdrawalLocktime);
    }
    if (message.tokenAmount.length !== 0) {
      writer.uint32(58).bytes(message.tokenAmount);
    }
    if (message.createTxHash.length !== 0) {
      writer.uint32(66).bytes(message.createTxHash);
    }
    if (message.createTxVoutIndex !== 0) {
      writer.uint32(72).uint32(message.createTxVoutIndex);
    }
    if (message.spendTxHash !== undefined) {
      writer.uint32(82).bytes(message.spendTxHash);
    }
    if (message.spendTxVoutIndex !== undefined) {
      writer.uint32(88).uint32(message.spendTxVoutIndex);
    }
    if (message.isFrozen !== undefined) {
      writer.uint32(96).bool(message.isFrozen);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SparkLeaf {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSparkLeaf();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tokenPublicKey = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.ownerPublicKey = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.revocationPublicKey = reader.bytes();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.withdrawalBondSats = longToNumber(reader.uint64());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.withdrawalLocktime = longToNumber(reader.uint64());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.tokenAmount = reader.bytes();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.createTxHash = reader.bytes();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.createTxVoutIndex = reader.uint32();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.spendTxHash = reader.bytes();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.spendTxVoutIndex = reader.uint32();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.isFrozen = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SparkLeaf {
    return {
      tokenPublicKey: isSet(object.tokenPublicKey) ? bytesFromBase64(object.tokenPublicKey) : new Uint8Array(0),
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      ownerPublicKey: isSet(object.ownerPublicKey) ? bytesFromBase64(object.ownerPublicKey) : new Uint8Array(0),
      revocationPublicKey: isSet(object.revocationPublicKey)
        ? bytesFromBase64(object.revocationPublicKey)
        : new Uint8Array(0),
      withdrawalBondSats: isSet(object.withdrawalBondSats) ? globalThis.Number(object.withdrawalBondSats) : 0,
      withdrawalLocktime: isSet(object.withdrawalLocktime) ? globalThis.Number(object.withdrawalLocktime) : 0,
      tokenAmount: isSet(object.tokenAmount) ? bytesFromBase64(object.tokenAmount) : new Uint8Array(0),
      createTxHash: isSet(object.createTxHash) ? bytesFromBase64(object.createTxHash) : new Uint8Array(0),
      createTxVoutIndex: isSet(object.createTxVoutIndex) ? globalThis.Number(object.createTxVoutIndex) : 0,
      spendTxHash: isSet(object.spendTxHash) ? bytesFromBase64(object.spendTxHash) : undefined,
      spendTxVoutIndex: isSet(object.spendTxVoutIndex) ? globalThis.Number(object.spendTxVoutIndex) : undefined,
      isFrozen: isSet(object.isFrozen) ? globalThis.Boolean(object.isFrozen) : undefined,
    };
  },

  toJSON(message: SparkLeaf): unknown {
    const obj: any = {};
    if (message.tokenPublicKey.length !== 0) {
      obj.tokenPublicKey = base64FromBytes(message.tokenPublicKey);
    }
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.ownerPublicKey.length !== 0) {
      obj.ownerPublicKey = base64FromBytes(message.ownerPublicKey);
    }
    if (message.revocationPublicKey.length !== 0) {
      obj.revocationPublicKey = base64FromBytes(message.revocationPublicKey);
    }
    if (message.withdrawalBondSats !== 0) {
      obj.withdrawalBondSats = Math.round(message.withdrawalBondSats);
    }
    if (message.withdrawalLocktime !== 0) {
      obj.withdrawalLocktime = Math.round(message.withdrawalLocktime);
    }
    if (message.tokenAmount.length !== 0) {
      obj.tokenAmount = base64FromBytes(message.tokenAmount);
    }
    if (message.createTxHash.length !== 0) {
      obj.createTxHash = base64FromBytes(message.createTxHash);
    }
    if (message.createTxVoutIndex !== 0) {
      obj.createTxVoutIndex = Math.round(message.createTxVoutIndex);
    }
    if (message.spendTxHash !== undefined) {
      obj.spendTxHash = base64FromBytes(message.spendTxHash);
    }
    if (message.spendTxVoutIndex !== undefined) {
      obj.spendTxVoutIndex = Math.round(message.spendTxVoutIndex);
    }
    if (message.isFrozen !== undefined) {
      obj.isFrozen = message.isFrozen;
    }
    return obj;
  },

  create(base?: DeepPartial<SparkLeaf>): SparkLeaf {
    return SparkLeaf.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SparkLeaf>): SparkLeaf {
    const message = createBaseSparkLeaf();
    message.tokenPublicKey = object.tokenPublicKey ?? new Uint8Array(0);
    message.id = object.id ?? "";
    message.ownerPublicKey = object.ownerPublicKey ?? new Uint8Array(0);
    message.revocationPublicKey = object.revocationPublicKey ?? new Uint8Array(0);
    message.withdrawalBondSats = object.withdrawalBondSats ?? 0;
    message.withdrawalLocktime = object.withdrawalLocktime ?? 0;
    message.tokenAmount = object.tokenAmount ?? new Uint8Array(0);
    message.createTxHash = object.createTxHash ?? new Uint8Array(0);
    message.createTxVoutIndex = object.createTxVoutIndex ?? 0;
    message.spendTxHash = object.spendTxHash ?? undefined;
    message.spendTxVoutIndex = object.spendTxVoutIndex ?? undefined;
    message.isFrozen = object.isFrozen ?? undefined;
    return message;
  },
};

function createBaseToken(): Token {
  return {
    name: "",
    symbol: "",
    publicKey: "",
    decimals: undefined,
    isFreezable: undefined,
    maxSupply: undefined,
    totalSupply: new Uint8Array(0),
    l1Supply: new Uint8Array(0),
    sparkSupply: new Uint8Array(0),
    totalOwnedByIssuer: new Uint8Array(0),
    totalFrozen: new Uint8Array(0),
  };
}

export const Token: MessageFns<Token> = {
  encode(message: Token, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.symbol !== "") {
      writer.uint32(18).string(message.symbol);
    }
    if (message.publicKey !== "") {
      writer.uint32(26).string(message.publicKey);
    }
    if (message.decimals !== undefined) {
      writer.uint32(32).uint32(message.decimals);
    }
    if (message.isFreezable !== undefined) {
      writer.uint32(40).bool(message.isFreezable);
    }
    if (message.maxSupply !== undefined) {
      writer.uint32(50).bytes(message.maxSupply);
    }
    if (message.totalSupply.length !== 0) {
      writer.uint32(58).bytes(message.totalSupply);
    }
    if (message.l1Supply.length !== 0) {
      writer.uint32(66).bytes(message.l1Supply);
    }
    if (message.sparkSupply.length !== 0) {
      writer.uint32(74).bytes(message.sparkSupply);
    }
    if (message.totalOwnedByIssuer.length !== 0) {
      writer.uint32(82).bytes(message.totalOwnedByIssuer);
    }
    if (message.totalFrozen.length !== 0) {
      writer.uint32(90).bytes(message.totalFrozen);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Token {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseToken();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.symbol = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.publicKey = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.decimals = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.isFreezable = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.maxSupply = reader.bytes();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.totalSupply = reader.bytes();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.l1Supply = reader.bytes();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.sparkSupply = reader.bytes();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.totalOwnedByIssuer = reader.bytes();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.totalFrozen = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Token {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      symbol: isSet(object.symbol) ? globalThis.String(object.symbol) : "",
      publicKey: isSet(object.publicKey) ? globalThis.String(object.publicKey) : "",
      decimals: isSet(object.decimals) ? globalThis.Number(object.decimals) : undefined,
      isFreezable: isSet(object.isFreezable) ? globalThis.Boolean(object.isFreezable) : undefined,
      maxSupply: isSet(object.maxSupply) ? bytesFromBase64(object.maxSupply) : undefined,
      totalSupply: isSet(object.totalSupply) ? bytesFromBase64(object.totalSupply) : new Uint8Array(0),
      l1Supply: isSet(object.l1Supply) ? bytesFromBase64(object.l1Supply) : new Uint8Array(0),
      sparkSupply: isSet(object.sparkSupply) ? bytesFromBase64(object.sparkSupply) : new Uint8Array(0),
      totalOwnedByIssuer: isSet(object.totalOwnedByIssuer)
        ? bytesFromBase64(object.totalOwnedByIssuer)
        : new Uint8Array(0),
      totalFrozen: isSet(object.totalFrozen) ? bytesFromBase64(object.totalFrozen) : new Uint8Array(0),
    };
  },

  toJSON(message: Token): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.symbol !== "") {
      obj.symbol = message.symbol;
    }
    if (message.publicKey !== "") {
      obj.publicKey = message.publicKey;
    }
    if (message.decimals !== undefined) {
      obj.decimals = Math.round(message.decimals);
    }
    if (message.isFreezable !== undefined) {
      obj.isFreezable = message.isFreezable;
    }
    if (message.maxSupply !== undefined) {
      obj.maxSupply = base64FromBytes(message.maxSupply);
    }
    if (message.totalSupply.length !== 0) {
      obj.totalSupply = base64FromBytes(message.totalSupply);
    }
    if (message.l1Supply.length !== 0) {
      obj.l1Supply = base64FromBytes(message.l1Supply);
    }
    if (message.sparkSupply.length !== 0) {
      obj.sparkSupply = base64FromBytes(message.sparkSupply);
    }
    if (message.totalOwnedByIssuer.length !== 0) {
      obj.totalOwnedByIssuer = base64FromBytes(message.totalOwnedByIssuer);
    }
    if (message.totalFrozen.length !== 0) {
      obj.totalFrozen = base64FromBytes(message.totalFrozen);
    }
    return obj;
  },

  create(base?: DeepPartial<Token>): Token {
    return Token.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Token>): Token {
    const message = createBaseToken();
    message.name = object.name ?? "";
    message.symbol = object.symbol ?? "";
    message.publicKey = object.publicKey ?? "";
    message.decimals = object.decimals ?? undefined;
    message.isFreezable = object.isFreezable ?? undefined;
    message.maxSupply = object.maxSupply ?? undefined;
    message.totalSupply = object.totalSupply ?? new Uint8Array(0);
    message.l1Supply = object.l1Supply ?? new Uint8Array(0);
    message.sparkSupply = object.sparkSupply ?? new Uint8Array(0);
    message.totalOwnedByIssuer = object.totalOwnedByIssuer ?? new Uint8Array(0);
    message.totalFrozen = object.totalFrozen ?? new Uint8Array(0);
    return message;
  },
};

function createBaseBlockInfo(): BlockInfo {
  return { blockHash: new Uint8Array(0), blockHeight: 0, minedAt: undefined };
}

export const BlockInfo: MessageFns<BlockInfo> = {
  encode(message: BlockInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.blockHash.length !== 0) {
      writer.uint32(10).bytes(message.blockHash);
    }
    if (message.blockHeight !== 0) {
      writer.uint32(16).uint32(message.blockHeight);
    }
    if (message.minedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.minedAt), writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BlockInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBlockInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.blockHash = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.blockHeight = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.minedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BlockInfo {
    return {
      blockHash: isSet(object.blockHash) ? bytesFromBase64(object.blockHash) : new Uint8Array(0),
      blockHeight: isSet(object.blockHeight) ? globalThis.Number(object.blockHeight) : 0,
      minedAt: isSet(object.minedAt) ? fromJsonTimestamp(object.minedAt) : undefined,
    };
  },

  toJSON(message: BlockInfo): unknown {
    const obj: any = {};
    if (message.blockHash.length !== 0) {
      obj.blockHash = base64FromBytes(message.blockHash);
    }
    if (message.blockHeight !== 0) {
      obj.blockHeight = Math.round(message.blockHeight);
    }
    if (message.minedAt !== undefined) {
      obj.minedAt = message.minedAt.toISOString();
    }
    return obj;
  },

  create(base?: DeepPartial<BlockInfo>): BlockInfo {
    return BlockInfo.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<BlockInfo>): BlockInfo {
    const message = createBaseBlockInfo();
    message.blockHash = object.blockHash ?? new Uint8Array(0);
    message.blockHeight = object.blockHeight ?? 0;
    message.minedAt = object.minedAt ?? undefined;
    return message;
  },
};

function createBaseTokenPubkey(): TokenPubkey {
  return { publicKey: new Uint8Array(0) };
}

export const TokenPubkey: MessageFns<TokenPubkey> = {
  encode(message: TokenPubkey, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.publicKey.length !== 0) {
      writer.uint32(10).bytes(message.publicKey);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TokenPubkey {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTokenPubkey();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.publicKey = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TokenPubkey {
    return { publicKey: isSet(object.publicKey) ? bytesFromBase64(object.publicKey) : new Uint8Array(0) };
  },

  toJSON(message: TokenPubkey): unknown {
    const obj: any = {};
    if (message.publicKey.length !== 0) {
      obj.publicKey = base64FromBytes(message.publicKey);
    }
    return obj;
  },

  create(base?: DeepPartial<TokenPubkey>): TokenPubkey {
    return TokenPubkey.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<TokenPubkey>): TokenPubkey {
    const message = createBaseTokenPubkey();
    message.publicKey = object.publicKey ?? new Uint8Array(0);
    return message;
  },
};

function createBaseTokenPubkeyAnnouncement(): TokenPubkeyAnnouncement {
  return {
    publicKey: undefined,
    name: "",
    symbol: "",
    decimal: new Uint8Array(0),
    maxSupply: new Uint8Array(0),
    isFreezable: false,
  };
}

export const TokenPubkeyAnnouncement: MessageFns<TokenPubkeyAnnouncement> = {
  encode(message: TokenPubkeyAnnouncement, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.publicKey !== undefined) {
      TokenPubkey.encode(message.publicKey, writer.uint32(10).fork()).join();
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.symbol !== "") {
      writer.uint32(26).string(message.symbol);
    }
    if (message.decimal.length !== 0) {
      writer.uint32(34).bytes(message.decimal);
    }
    if (message.maxSupply.length !== 0) {
      writer.uint32(42).bytes(message.maxSupply);
    }
    if (message.isFreezable !== false) {
      writer.uint32(48).bool(message.isFreezable);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TokenPubkeyAnnouncement {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTokenPubkeyAnnouncement();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.publicKey = TokenPubkey.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.symbol = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.decimal = reader.bytes();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.maxSupply = reader.bytes();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.isFreezable = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TokenPubkeyAnnouncement {
    return {
      publicKey: isSet(object.publicKey) ? TokenPubkey.fromJSON(object.publicKey) : undefined,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      symbol: isSet(object.symbol) ? globalThis.String(object.symbol) : "",
      decimal: isSet(object.decimal) ? bytesFromBase64(object.decimal) : new Uint8Array(0),
      maxSupply: isSet(object.maxSupply) ? bytesFromBase64(object.maxSupply) : new Uint8Array(0),
      isFreezable: isSet(object.isFreezable) ? globalThis.Boolean(object.isFreezable) : false,
    };
  },

  toJSON(message: TokenPubkeyAnnouncement): unknown {
    const obj: any = {};
    if (message.publicKey !== undefined) {
      obj.publicKey = TokenPubkey.toJSON(message.publicKey);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.symbol !== "") {
      obj.symbol = message.symbol;
    }
    if (message.decimal.length !== 0) {
      obj.decimal = base64FromBytes(message.decimal);
    }
    if (message.maxSupply.length !== 0) {
      obj.maxSupply = base64FromBytes(message.maxSupply);
    }
    if (message.isFreezable !== false) {
      obj.isFreezable = message.isFreezable;
    }
    return obj;
  },

  create(base?: DeepPartial<TokenPubkeyAnnouncement>): TokenPubkeyAnnouncement {
    return TokenPubkeyAnnouncement.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<TokenPubkeyAnnouncement>): TokenPubkeyAnnouncement {
    const message = createBaseTokenPubkeyAnnouncement();
    message.publicKey = (object.publicKey !== undefined && object.publicKey !== null)
      ? TokenPubkey.fromPartial(object.publicKey)
      : undefined;
    message.name = object.name ?? "";
    message.symbol = object.symbol ?? "";
    message.decimal = object.decimal ?? new Uint8Array(0);
    message.maxSupply = object.maxSupply ?? new Uint8Array(0);
    message.isFreezable = object.isFreezable ?? false;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
